/* fr.js — the French dictionary (headless-safe). Keys are the English exactly as `tr()` is
 * handed it (and the static HTML's text, whitespace collapsed), `{name}` placeholders kept by
 * name. A missing key falls back to the English. Held by 'every word has its French'. */
(function (global) {
  'use strict';
  Object.assign(global.I18N.FR, {
    "  (Chaos took {p}%)": "  (le Chaos en a pris {p} %)",
    " has set foot upon the Pattern!": " a posé le pied sur la Marelle !",
    " is three quarters of the way round the Pattern": " a parcouru les trois quarts de la Marelle",
    " nears the final veil of the Pattern!": " approche du dernier voile de la Marelle !",
    " walks the Pattern — halfway to the throne": " parcourt la Marelle — à mi-chemin du trône",
    " · began the walk at {t}": " · Marelle entamée à {t}",
    " · holding at home": " · tenant au logis",
    " · keeps {n}": " · garde {n}",
    " · never walked": " · jamais sur la Marelle",
    " · posted afield": " · posté en campagne",
    " · single target": " · cible unique",
    " · splash {n}": " · éclats {n}",
    " · tore a rival off the Pattern {n}x": " · rival arraché à la Marelle {n} fois",
    " · −{w}/s the walk": " · −{w}/s pour la marche",
    "(none)": "(aucun)",
    "+{i}/s income · −{m}/s muster": "+{i}/s de revenu · −{m}/s de levée",
    "+{n}◆/s from its spring": "+{n}◆/s tirés de sa source",
    "1) {who} scans this  2) tap SCAN REPLY": "1) {who} scanne ceci  2) touchez SCANNER LA RÉPONSE",
    "<b>✔ Finished.</b> Tap it again to see what it can do.": "<b>✔ Achevé.</b> Touchez-le de nouveau pour voir ce qu'il peut faire.",
    "<tr><th>lv</th><th>to raise</th><th>blow</th><th>every</th><th>range</th></tr>": "<tr><th>niv</th><th>pour élever</th><th>coup</th><th>cadence</th><th>portée</th></tr>",
    "<tr><th>lv</th><th>to raise</th><th>hp</th><th>blow</th><th>each</th><th>drain</th></tr>": "<tr><th>niv</th><th>pour élever</th><th>PV</th><th>coup</th><th>l'unité</th><th>drain</th></tr>",
    "A balanced hand — halls, stone and a Shrine — and he will take whichever of the two roads you leave open.": "Une main équilibrée — casernes, pierre et Sanctuaire — et il prendra celle des deux routes que vous laisserez ouverte.",
    "a blow every {n}s": "un coup toutes les {n} s",
    "a bot heir": "un héritier automate",
    "A cannon on a cart: it bursts where it lands and bites stone, but every tower out-reaches it. Nothing that gets close to it lives long enough to regret it.": "Un canon sur un chariot : il éclate où il tombe et mord la pierre, mais chaque tour le surpasse en portée. Rien de ce qui l'approche ne vit assez longtemps pour le regretter.",
    "a chained man marches at {p}% pace": "un homme enchaîné marche à {p} % de son allure",
    "a city": "une cité",
    "A COUNTRY OF CITIES": "UN PAYS DE CITÉS",
    "a court": "une cour",
    "a fiend already under {p}% of its life turns instead": "un démon déjà sous {p} % de sa vie se retourne plutôt",
    "a Gate draws Shadow out of the ground — it stands on a spring, and only there": "une Porte tire l'Ombre du sol — elle se dresse sur une source, et nulle part ailleurs",
    "A giant crossbow: one bolt, far and heavy. Champions and fiends fall to it — a marching crowd walks straight past.": "Une arbalète géante : un seul carreau, loin et lourd. Champions et démons tombent sous lui — une foule en marche passe tout droit.",
    "A grasping shadow-lord": "Un seigneur d'Ombre rapace",
    "a High Place": "un Haut Lieu",
    "a lord": "un seigneur",
    "a lord of Shadow": "un seigneur d’Ombre",
    "A Marcher Captain": "Un capitaine des Marches",
    "A milestone of the black road. Chaos favors this ground.": "Une borne de la route noire. Le Chaos affectionne ce sol.",
    "a neighbour": "un voisin",
    "A new shadow of Amber is drawn — it settles after this match": "Une nouvelle ombre d’Ambre se dessine — elle s’installera après cette partie",
    "A new standard": "Un nouvel étendard",
    "A NEW WAR — {n} HEIRS": "UNE NOUVELLE GUERRE — {n} HÉRITIERS",
    "a rival": "un rival",
    "a rival banner": "une bannière rivale",
    "A roofed ram on rollers. It must reach the wall to swing, and very little that reaches one survives it.": "Un bélier couvert, sur rouleaux. Il doit atteindre le mur pour frapper, et bien peu de ce qu'il atteint y survit.",
    "A run of stone. Nothing crosses it and nothing shoots through it. Men who come up to man it can be shot back — but the merlons take half of every blow that finds them.": "Un pan de pierre. Rien ne le franchit et rien ne tire au travers. Les hommes qui montent le garnir peuvent être visés en retour — mais les merlons prennent la moitié de chaque coup qui les trouve.",
    "A Seat cannot be thrown down in this war": "Un Siège ne peut être abattu dans cette guerre",
    "a Seat of Power": "un Siège de Pouvoir",
    "A Seat of Power.": "Un Siège de Pouvoir.",
    "A Shadow-ghost": "Un spectre d'Ombre",
    "a skirmish: one fresh board, first Seat to fall": "une escarmouche : un terrain neuf, le premier Siège à tomber perd",
    "A spring of living Shadow. Raise a Gate on it — your troops must be standing here — and it will pay for wars.": "Une source d'Ombre vivante. Élevez-y une Porte — vos troupes doivent s'y tenir — et elle paiera des guerres.",
    "a Spring of Shadow": "une Source d’Ombre",
    "a throw every {v}s, in place of his shot": "un jet toutes les {v} s, au lieu de son tir",
    "A unit of yours must stand there — plant the banner first": "Une de vos unités doit s’y tenir — plantez d’abord l’étendard",
    "A walk cannot be called off — the Pattern has you until a hundred, or until the Shrine falls": "On ne renonce pas à la Marelle — elle vous tient jusqu’à cent, ou jusqu’à la chute du Sanctuaire",
    "ADD ANOTHER HEIR": "AJOUTER UN HÉRITIER",
    "AGAINST YOU": "CONTRE VOUS",
    "AMBER": "AMBRE",
    "Amber is yours. The Pattern holds, and the black road answers to a name again.": "Ambre est à vous. La Marelle tient, et la route noire répond de nouveau à un nom.",
    "AMBER — no match recorded.": "AMBRE — aucune partie consignée.",
    "AMBER — nothing recorded.": "AMBRE — rien d'enregistré.",
    "Amber — The Succession": "Ambre — La Succession",
    "AMBER — THE SUCCESSION · chronicle of a match": "AMBRE — LA SUCCESSION · chronique d'une partie",
    "an heir": "un héritier",
    "An heir": "Un héritier",
    "An heir has left the link — pair again from the menu": "Un héritier a quitté le lien — appairez-vous de nouveau depuis le menu",
    "An heir has left the table — pair again from the menu": "Un héritier a quitté la table — appairez-vous de nouveau depuis le menu",
    "Android: Settings → Connections → Mobile Hotspot. The other phone joins it like any Wi-Fi.": "Android : Paramètres → Connexions → Point d’accès mobile. L’autre téléphone s’y connecte comme à n’importe quel Wi-Fi.",
    "Another heir": "Un autre héritier",
    "ANOTHER MATCH": "UNE AUTRE PARTIE",
    "Archer": "Archer",
    "Archers": "Archers",
    "Arden's rangers — half again as fast as anything on the board. They take springs and run down shooters.": "Les coureurs d'Arden — moitié plus rapides que quiconque sur le terrain. Ils prennent les sources et rattrapent les tireurs.",
    "ARMY": "ARMÉE",
    "Arrives first, with more. Halls before anything else, outriders to get there and a ram to get in. He wins early or not at all.": "Il arrive le premier, et en plus grand nombre. Des casernes avant toute chose, des éclaireurs pour y parvenir et un bélier pour entrer. Il gagne tôt, ou pas du tout.",
    "asked": "demandée",
    "asks for terms — tap to accept": "demande une trêve — touchez pour accepter",
    "asks terms — tap to accept": "demande une trêve — touchez pour accepter",
    "at least one — a war needs an enemy": "au moins un — une guerre exige un ennemi",
    "at terms with you": "en trêve avec vous",
    "at war — tap to offer": "en guerre — touchez pour offrir une trêve",
    "AWAITING THE HOST": "EN ATTENTE DE L’HÔTE",
    "BACK TO THE MENU": "RETOUR AU MENU",
    "BACK TO THE WAR": "RETOUR À LA GUERRE",
    "Ballista": "Baliste",
    "Ballista Tower": "Tour à baliste",
    "bands": "fascé",
    "Barracks": "Caserne",
    "Barracks and spires pay for troops again": "Casernes et flèches paient de nouveau pour des troupes",
    "Barrackss": "Casernes",
    "BEGIN": "COMMENCER",
    "BEGIN IN YOUR WAR": "COMMENCER DANS VOTRE GUERRE",
    "BEGIN THE WALK": "ENTAMER LA MARELLE",
    "BEGIN THE WAR": "OUVRIR LA GUERRE",
    "BEGIN — {n} HEIRS": "COMMENCER — {n} HÉRITIERS",
    "begun {t}": "commencée à {t}",
    "BEING CLAIMED — {n}s": "REVENDIQUÉE — {n} s",
    "Benedict is coming, and he is coming soon. You will not out-muster the Master of Arms in the open field.\n\nStone is the answer. A Curtain Wall is drawn as a RUN — tap where it starts, then where it ends — and it bars the ground to everyone but you. Archers posted to it take the parapet and throw from cover; everyone else forms ranks at its foot.\n\nHold your Seat for eight minutes.": "Benedict arrive, et il arrive bientôt. Vous ne lèverez pas plus d'hommes que le Maître d'Armes en rase campagne.\n\nLa pierre est la réponse. Une Courtine se trace comme un PAN — touchez là où il commence, puis là où il finit — et elle interdit le terrain à tous sauf à vous. Les archers qui y sont postés prennent le parapet et tirent à couvert ; tous les autres se rangent à son pied.\n\nTenez votre Siège huit minutes.",
    "Benedict, Master of Arms": "Benedict, Maître d'Armes",
    "besieges nothing · but strikes a Shrine": "n'assiège rien · mais frappe un Sanctuaire",
    "Beyond that company’s reach — take a city nearer to it": "Hors de la portée de cette compagnie — prenez une cité plus proche",
    "beyond your cities’ reach — take a city nearer to it": "hors de la portée de vos cités — prenez une cité plus proche",
    "beyond your writ — hold a Gate nearer, or take a spring": "hors de votre ban — tenez une Porte plus proche, ou prenez une source",
    "Beyond your writ — your Gates carry it outward": "Hors de votre ban — ce sont vos Portes qui l’étendent",
    "Binders": "Lieurs",
    "Bleys": "Bleys",
    "Bleys again, and this time he sends a herald before he sends a column. Terms: neither of you lifts a hand against the other. They are already sworn — you will find them in the corner of your board, and while they stand his men will walk past yours without a blow struck.\n\nUnderstand what you have bought. Not safety — TIME. An heir at peace needs no army to hold what he has, so every drop of essence that would have gone into a hall can go into the ground instead. Take springs. Take all of them.\n\nAnd understand what you have sold. He is raising men with the same quiet you are, and the Flame has never yet kept a promise longer than it was useful to him. There is no notice and there is no grace: the first you will know of it is your men dying. Tap his name to break first, if you think you can read the hour.\n\nHold four springs of Shadow, and keep them for two minutes.": "Bleys encore, et cette fois il envoie un héraut avant d'envoyer une colonne. Ses termes : nul de vous deux ne lèvera la main contre l'autre. Ils sont déjà jurés — vous les trouverez dans le coin de votre carte, et tant qu'ils tiennent ses hommes passeront à côté des vôtres sans qu'un coup soit porté.\n\nComprenez ce que vous avez acheté. Non pas la sûreté — le TEMPS. Un héritier en paix n'a nul besoin d'armée pour tenir ce qu'il a, et chaque goutte d'essence qui serait allée dans une caserne peut aller dans la terre à la place. Prenez des sources. Prenez-les toutes.\n\nEt comprenez ce que vous avez vendu. Il lève des hommes dans le même calme que vous, et la Flamme n'a jamais tenu une promesse plus longtemps qu'elle ne lui était utile. Il n'y aura ni préavis ni grâce : la première chose que vous en saurez, c'est la mort de vos hommes. Touchez son nom pour rompre le premier, si vous croyez savoir lire l'heure.\n\nTenez quatre sources de l'Ombre, et gardez-les deux minutes.",
    "Bleys of the Flame": "Bleys de la Flamme",
    "Bleys of the Flame again, with the same realm behind him as the day you burned his forward wells. Nothing about him has changed — and he has no patience for the lines, so he will not be walking anywhere. The other road is yours alone.\n\nWhat has changed is what you mean to do while he comes. A walk drains your essence BEFORE your halls are paid: step on early and you muster nobody for five and a half minutes. Take springs first — the Pattern is bought with Shadow Gates.\n\nAnd a walk is a public act. The moment you set foot on the lines your Shrine burns on every board in the game, so he will know exactly where to send his army; throw the Shrine down and the walker is torn off the Pattern. It cannot be called off, and there is no second attempt inside one match.\n\nWalk the Pattern to its heart.": "Bleys de la Flamme encore, avec derrière lui le même royaume que le jour où vous avez incendié ses puits avancés. Rien en lui n'a changé — et il n'a nulle patience pour les lignes, aussi ne parcourra-t-il rien du tout. L'autre route est à vous seul.\n\nCe qui a changé, c'est ce que vous comptez faire pendant qu'il vient. Le parcours saigne votre essence AVANT que vos casernes ne soient payées : engagez-vous trop tôt et vous ne lèverez personne pendant cinq minutes et demie. Prenez d'abord des sources — la Marelle s'achète avec des Portes d'Ombre.\n\nEt parcourir la Marelle est un acte public. À l'instant où vous posez le pied sur les lignes, votre Sanctuaire brûle sur toutes les cartes de la partie, et il saura exactement où envoyer son armée ; abattez le Sanctuaire et celui qui marche est arraché à la Marelle. Le parcours ne peut être interrompu, et il n'y a pas de seconde tentative au cours d'une même partie.\n\nParcourez la Marelle jusqu'en son cœur.",
    "Bleys of the Flame is taking Shadow while you count your wells. He raises his Gates in the open and trusts his host to keep them.\n\nA mustering hall flies a standard of its own, and the tray at your thumb is one chip per company. Raise halls, arm a standard, and send it.\n\nThrow down the Gates he has taken out in Shadow. The well under his own guns is a matter for another day.": "Bleys de la Flamme s'empare de l'Ombre pendant que vous comptez vos puits. Il élève ses Portes à découvert et se fie à son ost pour les garder.\n\nUne caserne arbore un étendard qui lui est propre, et le plateau sous votre pouce porte une pastille par compagnie. Élevez des casernes, armez un étendard, et envoyez-le.\n\nAbattez les Portes qu'il a prises au loin dans l'Ombre. Le puits sous ses propres canons est l'affaire d'un autre jour.",
    "Bombard": "Bombarde",
    "Bombards": "Bombardes",
    "BOT HEIRS": "HÉRITIERS AUTOMATES",
    "bots": "automates",
    "Bowmen — one of the two who can stand on your stone. Raise them if you own walls and towers to fill.": "Des archers — l'un des deux qui peuvent se tenir sur votre pierre. Levez-les si vous avez des murs et des tours à garnir.",
    "Brand the Unmaker": "Brand le Défaiseur",
    "Break his Seat of Power": "Brisez son Siège de Pouvoir",
    "BUILD": "BÂTIR",
    "build {bt}": "bâtir : {name} ({bt})",
    "building": "ouvrage",
    "Builds Bombards: guns on carts that burst where they land and bite stone — under the towers' reach, so they arrive escorted.": "Construit des Bombardes : des pièces sur affût roulant qui éclatent où elles tombent et mordent la pierre — sous la portée des tours, aussi arrivent-elles escortées.",
    "Builds Engines — slow, and made for stone rather than men. At level 2 the yard is RE-TOOLED for rams or for bombards, and there is no going back.": "Construit des Engins — lents, et faits pour la pierre plutôt que pour les hommes. Au niveau 2, l'atelier est RÉOUTILLÉ pour les béliers ou pour les bombardes, et l'on ne revient pas en arrière.",
    "Builds Rams: twice an Engine's bite and twice its stone, and they must reach the wall to swing.": "Construit des Béliers : deux fois la morsure d'un Engin et deux fois sa pierre, et ils doivent atteindre le mur pour frapper.",
    "Call a halt": "Décréter une halte",
    "Call the storm upon any place you can see. It breaks an army; it does not erase one.": "Appelez la tempête sur tout lieu que vous voyez. Elle brise une armée ; elle ne l'efface pas.",
    "called by {who}": "ordonnée par {who}",
    "camera blocked — allow camera access": "caméra bloquée — autorisez l’accès à la caméra",
    "CAMPAIGN": "CAMPAGNE",
    "campaign": "campagne",
    "campaign · {key}": "campagne · {key}",
    "Cannon": "Canon",
    "Cannon Tower": "Tour à canon",
    "Champion": "Champion",
    "Change its standard": "Changer son étendard",
    "Channel Essence to walk the Pattern. 100% claims the throne. The walk is REVEALED, it CANNOT be called off, and it is paid before your halls are — a walker who cannot carry the drain musters nobody.": "Canalisez l'Essence pour parcourir la Marelle. 100 % vous donne le trône. Le parcours est RÉVÉLÉ, il ne peut PAS être interrompu, et il est payé avant vos casernes — qui ne peut porter cette saignée ne lève plus personne.",
    "Chaos": "Le Chaos",
    "Chaos Fiend": "Démon du Chaos",
    "Chaos tears a rift": "le Chaos ouvre une faille",
    "Chaos tears open a rift in the black road": "Le Chaos ouvre une faille dans la route noire",
    "Cheap, quick, and gone before the answer arrives. They take springs and hunt whatever shoots at you.": "Bon marché, rapides, et partis avant que la riposte n'arrive. Ils prennent les sources et traquent tout ce qui vous tire dessus.",
    "checkers": "échiqueté",
    "CHOOSE YOUR RIVAL": "CHOISISSEZ VOTRE RIVAL",
    "cities held": "cités tenues",
    "CLAIMING — {n}s": "REVENDICATION — {n} s",
    "Clear the ground for something else — {n}◆ of the stone comes back. It cannot be undone.": "Libérer le terrain pour autre chose — {n}◆ de pierre vous reviennent. C'est sans retour.",
    "CLOSE": "FERMER",
    "Close": "Fermer",
    "company {co} standard": "étendard de la compagnie {co}",
    "Corwin": "Corwin",
    "Corwin of Amber": "Corwin d'Ambre",
    "Corwin’s trick — shadow-rouge that burns where Amber’s powder will not. It bursts over a column; against one great foe it is a firework.": "L'astuce de Corwin — le rouge d'Ombre qui brûle là où la poudre d'Ambre refuse. Il éclate au-dessus d'une colonne ; contre un seul grand ennemi, ce n'est qu'un feu d'artifice.",
    "could not draw the QR": "impossible de dessiner le QR",
    "could not draw the reply QR": "impossible de dessiner le QR de réponse",
    "crews idle": "équipes oisives",
    "Curtain Wall": "Courtine",
    "Curtain Walls": "Courtines",
    "Do not lose your {work}": "Ne perdez pas votre {work}",
    "dots": "semé de besants",
    "Drains Essence, and the drain comes before your halls are paid. Your rival WILL know. There is no turning back.": "Draine l'essence, et ce drain passe avant la solde de vos casernes. Votre rival le SAURA. Il n'y a pas de retour.",
    "drawing your Trump…": "votre Atout se dessine…",
    "Drive this court yourself — its purse, its crews and its standards answer your taps. The one you leave goes back to its own lord": "Menez vous-même cette cour — sa bourse, ses équipes et ses étendards répondent à vos touches. Celle que vous quittez revient à son propre seigneur",
    "each his own banner, played by the host": "chacun sa propre bannière, joués par l’hôte",
    "each human his own banner; tap for two sides": "chaque humain sa propre bannière ; touchez pour deux camps",
    "Elite ": "Élite ",
    "Elite {name}": "{name} d'élite",
    "Eric": "Eric",
    "ESSENCE": "ESSENCE",
    "essence a second": "essence par seconde",
    "Essence is out on the map: march men to a spring, then TAP THE SPRING to raise a Gate": "L’essence est dehors, sur la carte : menez des hommes à une source, puis TOUCHEZ LA SOURCE pour élever une Porte",
    "Every hall under this standard stops mustering — the rest of the realm carries on": "Chaque caserne sous cet étendard cesse de lever — le reste du royaume continue",
    "EVERY HEIR FOR HIMSELF": "CHAQUE HÉRITIER POUR SOI",
    "Every standard is struck and the whole army turns for home — defend the city": "Chaque étendard est abattu et toute l'armée rentre au logis — défendez la cité",
    "failed: {err}": "échec : {err}",
    "Far sight over Shadow, and arrows for trespassers. At level 2 the tower is REBUILT — ballista or cannon, and there is no going back": "La vue porte loin sur l'Ombre, et des flèches pour les intrus. Au niveau 2, la tour est REBÂTIE — baliste ou canon, et l'on ne revient pas en arrière",
    "Fewer men and heavier ones. They hold ground and a gateway, and a storm does not sweep them off it.": "Moins d'hommes, et plus lourds. Ils tiennent le terrain et une porte, et une tempête ne les en balaie pas.",
    "Fiends of Chaos — a foe of everyone": "Démons du Chaos — ennemis de tous",
    "finding a route to this phone…": "recherche d’une route vers ce téléphone…",
    "Fiona": "Fiona",
    "FOUR IS THE LIMIT": "QUATRE AU PLUS",
    "Four wells held through the storm. The road gives nothing back that is guarded.": "Quatre puits tenus à travers la tempête. La route ne rend rien de ce qui est gardé.",
    "Fragile, deadly at range, and the longest reach that can stand on a wall. He does not touch stone.": "Fragile, mortel à distance, et la plus longue portée qui puisse tenir un mur. Il ne touche pas à la pierre.",
    "FREE FOR ALL": "CHACUN POUR SOI",
    "free for all — {c} contenders, {m} minor lords": "chacun pour soi — {c} prétendants, {m} seigneurs mineurs",
    "From your own snapshots: a rival's essence never crosses the wire, and veiled works are not counted.": "D'après vos propres instantanés : l'essence d'un rival ne traverse jamais le fil, et les ouvrages voilés ne sont pas comptés.",
    "Go on": "Reprendre",
    "Green: hoards his essence, forgets his halls, and feeds you his army a handful at a time — and will not march on your Seat for thirteen minutes.": "Novice : il thésaurise son essence, oublie ses casernes et vous jette son armée par poignées — et il ne marchera pas sur votre Siège avant treize minutes.",
    "growing the country — a moment…": "le pays prend forme — un instant…",
    "Half the stone, and as many crews as you can spare — fewer crews, longer work. It shelters nobody until they are done.": "La moitié de la pierre, et autant d'équipes que vous pouvez en détacher — moins d'équipes, plus long travail. Il n'abrite personne tant qu'ils n'ont pas fini.",
    "hall → company {co}": "caserne → compagnie {co}",
    "Halt Standard {n}": "Arrêter l'Étendard {n}",
    "halt the muster": "suspendre la levée",
    "HALTED": "HALTE",
    "He throws chains of Shadow on a rival's men: they march slower and every blow lands harder while the chains hold. A Chaos fiend already beaten turns instead — Shadow will not hold it long.": "Il jette des chaînes d'Ombre sur les hommes d'un rival : ils marchent plus lentement et chaque coup porte plus fort tant que tiennent les chaînes. Un démon du Chaos déjà vaincu change de camp — l'Ombre ne le retiendra pas longtemps.",
    "HEIR": "HÉRITIER",
    "heir {i}": "héritier {i}",
    "High ground over the paths. A Watchtower here sees far and shoots farther.": "Une hauteur dominant les chemins. Une Tour de guet ici voit loin et tire plus loin encore.",
    "His wells are broken and his muster runs dry. An army is for taking things.": "Ses puits sont brisés et sa levée tarit. Une armée sert à prendre.",
    "Hold your Seat of Power for {secs} seconds": "Tenez votre Siège de Pouvoir {secs} secondes",
    "Hold your Seat — {s}s": "Tenez votre Siège — {s} s",
    "Hold {n} springs of Shadow, and keep them for {secs} seconds": "Tenez {n} sources de l'Ombre, et gardez-les {secs} secondes",
    "Hold {n} springs — you draw from {h}": "Tenez {n} sources — vous puisez à {h}",
    "Hold {n} springs — {s}s": "Tenez {n} sources — {s} s",
    "holding at home": "tient au logis",
    "holds a parapet, and shelters inside a tower ({n} to a tower)": "tient un parapet, et s'abrite dans une tour ({n} par tour)",
    "HOST THE TABLE": "TENIR LA TABLE",
    "humans and bots in two banners; tap for a free-for-all": "humains et automates en deux bannières ; touchez pour chacun pour soi",
    "I · The Shadow Road": "I · La Route d'Ombre",
    "I · THE SHADOW ROAD": "I · LA ROUTE D'OMBRE",
    "II · The Muster": "II · La Levée",
    "II · THE MUSTER": "II · LA LEVÉE",
    "III · The Curtain": "III · La Courtine",
    "III · THE CURTAIN": "III · LA COURTINE",
    "INCOME": "REVENU",
    "iPhone: Settings → Personal Hotspot → Allow Others to Join. The other phone joins it like any Wi-Fi.": "iPhone : Réglages → Partage de connexion → Autoriser d’autres utilisateurs. L’autre téléphone s’y connecte comme à n’importe quel Wi-Fi.",
    "It comes out of a rift and it hates everyone equally. It grows with the hour, and it can be BOUND.": "Il sort d'une faille et hait tout le monde également. Il grandit avec l'heure, et il peut être LIÉ.",
    "It gathered no Wi-Fi address at all, so there is no network for the other phone to reach it on. <b>Join a Wi-Fi network, or make this phone a hotspot.</b>": "Il n’a recueilli aucune adresse Wi-Fi : il n’y a donc aucun réseau par lequel l’autre téléphone puisse le joindre. <b>Rejoignez un réseau Wi-Fi, ou faites de ce téléphone un point d’accès.</b>",
    "It is already as high as it goes": "Il est déjà aussi haut qu’il peut l’être",
    "It is not finished yet": "Ce n’est pas encore achevé",
    "It stands and it can be broken, but it does its job for nobody until they are out of it.": "Il tient debout et peut être brisé, mais il ne sert personne tant qu'ils n'en sont pas sortis.",
    "It still answers to an heir — break it first": "Elle répond encore à un héritier — brisez-la d’abord",
    "Its halls pay for troops again": "Ses casernes paient de nouveau pour des troupes",
    "its sides are set — the heirs at the table take its seats in join order": "ses camps sont fixés — les héritiers de la table prennent ses places dans l’ordre d’arrivée",
    "IV · The Black Road": "IV · La Route noire",
    "IV · THE BLACK ROAD": "IV · LA ROUTE NOIRE",
    "Jewel of Judgment": "Joyau du Jugement",
    "JOIN A TABLE": "REJOINDRE UNE TABLE",
    "Julian, Warden of Arden": "Julian, Gardien d'Arden",
    "LAN": "LAN",
    "LAN {n}-way": "LAN à {n}",
    "LASTED": "DURÉE",
    "Leaving ends the table for everyone — press back again to end it": "Partir met fin à la table pour tous — appuyez encore sur retour pour y mettre fin",
    "level 1": "niveau 1",
    "Level 1": "Niveau 1",
    "Level {l} — choose once": "Niveau {l} — choisir une fois",
    "link code truncated": "code de liaison tronqué",
    "link code: trailing bytes": "code de liaison : octets en trop",
    "link code: unknown P2 version": "code de liaison : version P2 inconnue",
    "link code: varint": "code de liaison : varint invalide",
    "link lost": "lien perdu",
    "LINKED — awaiting the host…": "LIÉ — en attente de l’hôte…",
    "longer than your masons reach — hold more Gates, or draw a shorter run": "plus long que ne l'atteignent vos maçons — tenez plus de Portes, ou tracez un pan plus court",
    "MARSHAL": "MARÉCHAL",
    "marshal": "maréchal",
    "mason crews — idle of total": "équipes de maçons — libres sur total",
    "men afield": "hommes en campagne",
    "Men of {court} — {rel}": "Hommes de {court} — {rel}",
    "Mend the breach": "Réparer la brèche",
    "mends {v}/s": "soigne {v}/s",
    "mends {v}/s out to {r}": "soigne {v}/s jusqu'à {r}",
    "MENU": "MENU",
    "Mines Shadow before he fights: springs, Gates, then the Pattern once the ground will pay for the walk. Leave him alone and he simply wins.": "Il exploite l'Ombre avant de combattre : des sources, des Portes, puis la Marelle dès que la terre peut payer le parcours. Laissez-le en paix et il gagne, tout simplement.",
    "Move this hall to another company, or back under the Banner": "Passer cette caserne à une autre compagnie, ou la remettre sous la Bannière",
    "mustering nobody": "ne lève personne",
    "mustering nobody: resume this standard": "ne lève personne : reprendre cet étendard",
    "mustering: halt this standard": "lève des troupes : arrêter cet étendard",
    "Musters Soldiers who march the black road. At level 2 the hall is RE-RAISED around one soldiery — shieldwall, outriders or bowmen — and there is no going back.": "Lève des Soldats qui foulent la route noire. Au niveau 2, la caserne est RÉÉDIFIÉE autour d'une seule troupe — mur de boucliers, éclaireurs ou archers — et l'on ne revient pas en arrière.",
    "never": "jamais",
    "no gate": "sans porte",
    "no hall under it yet": "aucune caserne sous lui encore",
    "no link after 20s — tap HOST THE TABLE to draw a fresh Trump and try again": "aucun lien après 20 s — touchez TENIR LA TABLE pour dessiner un nouvel Atout et réessayer",
    "No link — tap HOST THE TABLE to try again": "Aucun lien — touchez TENIR LA TABLE pour réessayer",
    "no lord": "sans seigneur",
    "No lord of your banner can reach your court": "Aucun seigneur de votre bannière ne peut atteindre votre cour",
    "no offer is waiting — tap HOST THE TABLE first": "aucune offre n’attend — touchez d’abord TENIR LA TABLE",
    "no seat could be dealt to — pair again": "aucune place n’a pu être distribuée — appairez-vous de nouveau",
    "no stance given — his geography decides: a warden on the frontier, a steward inside": "aucune posture donnée — sa géographie décide : gardien sur la frontière, intendant à l'intérieur",
    "no troops of yours stand there to claim it": "aucune de vos troupes ne s'y tient pour la revendiquer",
    "nobody (unfinished)": "personne (inachevée)",
    "Not enough Essence": "Pas assez d’Essence",
    "NOTE: recorded from a guest's own snapshots — rival numbers are what you could SEE, not the truth.": "NOTE : consignée à partir des seuls instantanés d'un invité — les chiffres des rivaux sont ce que vous pouviez VOIR, non la vérité.",
    "Nothing is held back now. Benedict, Master of Arms, with a realm behind him and no reason to wait.\n\nA Seat is two and a half thousand hit points behind whatever he has raised around it, and a host of archers cannot scratch it — a shooter has no target among works at all. Bring something that breaks stone.\n\nTake the throne.": "Plus rien n'est retenu désormais. Benedict, Maître d'Armes, avec un royaume derrière lui et nulle raison d'attendre.\n\nUn Siège, ce sont deux mille cinq cents points de vie derrière tout ce qu'il a élevé autour, et un ost d'archers ne saurait l'égratigner — un tireur n'a aucune cible parmi les ouvrages. Amenez de quoi briser la pierre.\n\nPrenez le trône.",
    "Now tap where the wall should END": "Touchez maintenant où la courtine doit FINIR",
    "Now tap where the wall should END — the masons reach {n}": "Touchez maintenant où la courtine doit FINIR — les maçons portent jusqu’à {n}",
    "Oberon is gone and the black road is rising. You hold one spring and one hall, which is what any heir holds — and it is not a realm.\n\nEssence lies out in Shadow, at the springs. A Shadow Gate draws from one, and a Gate may only be raised where your own troops are standing.\n\nTake three springs. Julian will not trouble you yet.": "Obéron a disparu et la route noire monte. Vous tenez une source et une caserne, ce que tient tout héritier — et ce n'est pas un royaume.\n\nL'essence repose au loin dans l'Ombre, aux sources. Une Porte d'Ombre puise à l'une d'elles, et une Porte ne peut être élevée que là où se tiennent vos propres troupes.\n\nPrenez trois sources. Julian ne vous inquiétera pas encore.",
    "Oberon is gone. The black road reaches for the one true city.": "Obéron n'est plus. La route noire s'étend vers l'unique cité véritable.",
    "offered": "offerte",
    "one banner, one victory": "une bannière, une victoire",
    "One country, sixteen thrones, one Pattern. Two to four heirs contend for it in two sides; the rest of the country is minor lords who hold ground and swear to whoever breaks them. An heir at your side is your ally — one banner, one victory — not your vassal.": "Un pays, seize trônes, une Marelle. Deux à quatre héritiers se la disputent en deux camps ; le reste du pays n'est que seigneurs mineurs qui tiennent leurs terres et prêtent serment à quiconque les brise. Un héritier à vos côtés est votre allié — une bannière, une victoire — non votre vassal.",
    "One country, sixteen thrones, one Pattern. Two to four heirs contend for it, every one for himself; the rest of the country is minor lords who hold ground and swear to whoever breaks them. Terms may be sworn and broken — and whoever walks the Pattern finds the rest allied against him.": "Un pays, seize trônes, une Marelle. Deux à quatre héritiers se la disputent, chacun pour soi ; le reste du pays n'est que seigneurs mineurs qui tiennent leurs terres et prêtent serment à quiconque les brise. Les trêves se jurent et se rompent — et celui qui parcourt la Marelle trouve tous les autres liés contre lui.",
    "One land, sixteen thrones, one Pattern. Put it down and pick it up.": "Une terre, seize trônes, une Marelle. Laissez-la, reprenez-la.",
    "One land, ten thrones, one Pattern. Put it down and pick it up.": "Une terre, dix trônes, une Marelle. Laissez-la, reprenez-la.",
    "One rival of your choosing, on fresh ground.": "Un rival de votre choix, sur une terre nouvelle.",
    "Only a curtain has a sheltered side to turn about": "Seule une courtine a une face abritée à retourner",
    "OPEN HOTSPOT SETTINGS": "OUVRIR LES RÉGLAGES DU PARTAGE DE CONNEXION",
    "ordered against {court}": "envoyé contre {court}",
    "ordered to support {court}": "envoyé soutenir {court}",
    "ordered: march on {name}": "ordre : marcher sur {name}",
    "ordered: support {name}": "ordre : soutenir {name}",
    "Outrider": "Éclaireur",
    "Outriders": "Éclaireurs",
    "Pairing failed — {err}": "L’appairage a échoué — {err}",
    "pale": "pal",
    "Pattern Shrine": "Sanctuaire de la Marelle",
    "Pattern Shrines": "Sanctuaires de la Marelle",
    "PEAK ARMY": "ARMÉE MAX.",
    "PEAK WORKS": "OUVRAGES MAX.",
    "plain": "uni",
    "Point at your rival’s Trump": "Visez l’Atout de votre rival",
    "posted afield": "posté en campagne",
    "power: {name}": "pouvoir : {name}",
    "PRINCE": "PRINCE",
    "QR scanning unsupported here": "scan de QR non pris en charge ici",
    "quartered": "écartelé",
    "Raise a company of its own, with its own flag in the tray": "Lever une compagnie à part, avec son propre fanion dans la barre",
    "Raise a Pattern Shrine first — there is nothing to walk from": "Élevez d’abord un Sanctuaire de la Marelle — il n’y a rien d’où partir",
    "Raise a work": "Élever un ouvrage",
    "Raise your works, walk in Shadow, and take the throne — by siege, or by the Pattern.": "Élevez vos ouvrages, cheminez dans l'Ombre et prenez le trône — par le siège, ou par la Marelle.",
    "Raise {n} {works}": "Élevez {n} {works}",
    "Raise {n} {works} — you hold {h}": "Élevez {n} {works} — vous en tenez {h}",
    "Raised by nobody: what you meet rather than what you muster.": "Levés par personne : ce que l'on rencontre plutôt que ce que l'on lève.",
    "Raised ON a spring of Shadow, and only there. It draws deep, and your writ runs where your Gates stand.": "Élevée SUR une source de l'Ombre, et là seulement. Elle puise profond, et votre ban s'étend où se dressent vos Portes.",
    "Rams": "Béliers",
    "Re-raise the hall around one kind of soldiery.": "Rebâtir la caserne autour d'une seule sorte de troupe.",
    "Re-tool the yard.": "Réoutiller l'atelier.",
    "reading the Trump… {have}/{need}": "lecture de l’Atout… {have}/{need}",
    "Rebuild it.": "Rebâtissez-le.",
    "Rebuild the tower.": "Rebâtir la tour.",
    "REMATCH": "REVANCHE",
    "result: abandoned at {t}": "issue : abandonnée à {t}",
    "result: LOST at {t} — by {reason}, to {who}": "issue : PERDUE à {t} — par {reason}, vainqueur : {who}",
    "result: WON at {t} — by {reason}, to {who}": "issue : GAGNÉE à {t} — par {reason}, vainqueur : {who}",
    "Resume Standard {n}": "Reprendre l'Étendard {n}",
    "resume the muster": "reprendre la levée",
    "RIVAL HEIRS": "HÉRITIERS RIVAUX",
    "same Wi-Fi · no server · pair by QR · two to four heirs": "même Wi-Fi · sans serveur · appairage par QR · deux à quatre héritiers",
    "SAVE": "ENREGISTRER",
    "scan cancelled": "scan annulé",
    "SCAN REPLY": "SCANNER LA RÉPONSE",
    "sealed": "scellée",
    "Sealed until the chapter before it is done.": "Scellé tant que le chapitre précédent n'est pas achevé.",
    "Seasoned but fallible, and at your gate not long after you have a realm.": "Aguerri mais faillible, et à votre porte peu après que vous tenez un royaume.",
    "seat {i}": "place {i}",
    "seat {n}": "siège {n}",
    "seats: {list}   (you are seat {i})": "sièges : {list}   (vous êtes le siège {i})",
    "SELECT IT ALL AND COPY": "SÉLECTIONNEZ TOUT ET COPIEZ",
    "Send them to a spring — the glowing pools out in Shadow": "Envoyez-les à une source — les bassins luisants, au loin dans l'Ombre",
    "Sends Shadow-binders, who chain a rival's men: chained men march slower and take heavier blows. A beaten fiend they chain turns instead.": "Envoie des Lieurs d'Ombre, qui enchaînent les hommes d'un rival : enchaînés, ils marchent plus lentement et encaissent des coups plus lourds. Un démon vaincu qu'ils enchaînent change de camp.",
    "Sends Sorcerers — fragile, deadly at range, and no use at all against stone. At level 2 the Spire turns to ONE art, mending or binding, and there is no going back.": "Envoie des Sorciers — fragiles, mortels à distance, et d'aucune utilité contre la pierre. Au niveau 2, la Flèche se voue à UN seul art, guérir ou lier, et l'on ne revient pas en arrière.",
    "Sends Wardens, who MEND the men beside them. Nothing else in Amber heals a wound.": "Envoie des Gardiens, qui SOIGNENT les hommes à leurs côtés. Rien d'autre en Ambre ne referme une blessure.",
    "Shadow Gate": "Porte d'Ombre",
    "Shadow Gates": "Portes d'Ombre",
    "SHADOW GATES": "PORTES D'OMBRE",
    "SHADOW {n}": "OMBRE {n}",
    "Shadow-binder": "Lieur d'Ombre",
    "Shadow-drawn infantry. He marches, he fights, and he will pull a wall down given long enough.": "Fantassin tiré de l'Ombre. Il marche, il se bat, et il abattra un mur si on lui en laisse le temps.",
    "Shieldman": "Porte-bouclier",
    "Shieldwall": "Mur de boucliers",
    "show this reply to Corwin — linking…": "montrez cette réponse à Corwin — liaison…",
    "Siege Engine": "Engin de siège",
    "Siege Ram": "Bélier de siège",
    "Siege Works": "Atelier de siège",
    "Siege Workss": "Ateliers de siège",
    "skirmish": "escarmouche",
    "SKIRMISH": "ESCARMOUCHE",
    "Slow, fragile in a fight, and worth four soldiers against stone. It arrives escorted or it does not arrive.": "Lent, fragile au combat, et il vaut quatre soldats contre la pierre. Il arrive escorté, ou il n'arrive pas.",
    "Soldier": "Soldat",
    "Sorcerer": "Sorcier",
    "Sorcery Spire": "Flèche de sorcellerie",
    "Sorcery Spires": "Flèches de sorcellerie",
    "splash {v}": "éclats {v}",
    "splash {v} at {p}%": "éclats {v} à {p} %",
    "SQUIRE": "ÉCUYER",
    "stance: MARSHAL — an army for your banner, goes where it fights": "posture : MARÉCHAL — une armée pour votre bannière, va où l'on se bat",
    "stance: STEWARD — grows the country, takes the springs in reach": "posture : INTENDANT — fait croître le pays, prend les sources à portée",
    "stance: WARDEN — holds and fortifies the court": "posture : GARDIEN — tient et fortifie la cour",
    "Standard {n}": "Étendard {n}",
    "STEWARD": "INTENDANT",
    "steward": "intendant",
    "steward by default": "intendant par défaut",
    "Stone and patience. Towers first, ground held rather than taken, and the Pattern only at the last — he is the slowest of them to reach for your throne.": "Pierre et patience. Les tours d'abord, le terrain tenu plutôt que pris, et la Marelle seulement à la fin — de tous, c'est lui le plus lent à tendre la main vers votre trône.",
    "Stop paying for new troops while the treasury gathers": "Cesser de payer de nouvelles troupes le temps que le trésor s'emplisse",
    "stripes": "rayé",
    "Summon the family champion at your gate (one at a time)": "Invoquez le champion de la famille à votre porte (un seul à la fois)",
    "sworn to you": "votre vassal",
    "sworn to {who}": "lié par serment à {who}",
    "tap anywhere to go on": "touchez n'importe où pour reprendre",
    "tap to move to the other side": "touchez pour passer dans l’autre camp",
    "TAP YOUR OWN TROOPS to pick up their standard, then tap where they should stand": "TOUCHEZ VOS TROUPES pour saisir leur étendard, puis touchez l’endroit où elles doivent se tenir",
    "terms offered": "trêve offerte",
    "terms with {who}": "trêve avec {who}",
    "That hall stands outside the city’s reach — only overlapping reaches share halls": "Cette caserne se dresse hors de la portée de la cité — seules des portées qui se chevauchent partagent leurs casernes",
    "That power is not ready": "Ce pouvoir n’est pas prêt",
    "that spring is already drawn upon": "cette source est déjà puisée",
    "The alarm has run its span — the lords return to their stances": "L’alarme a fait son temps — les seigneurs reprennent leur posture",
    "The alarm is lifted — the court is quiet, the lords return to their stances": "L’alarme est levée — la cour est calme, les seigneurs reprennent leur posture",
    "the Amber Rill": "le Ru d'Ambre",
    "The Binding": "Le Lien",
    "The black road is open and Chaos is spilling through it. Brand the Unmaker is content to let it come — every fiend that gnaws your Gates is one he need not pay for.\n\nChaos is the weather. It cannot take your Seat, and it will take everything else if you let it: a forward Gate is exactly what it comes for, and the men who took the spring are its garrison.\n\nDraw from four springs, and keep all four for two minutes together.": "La route noire est ouverte et le Chaos s'y déverse. Brand le Défaiseur se contente de le laisser venir — chaque démon qui ronge vos Portes en est un qu'il n'a pas à payer.\n\nLe Chaos est le temps qu'il fait. Il ne peut prendre votre Siège, et il prendra tout le reste si vous le laissez faire : une Porte avancée est précisément ce qu'il vient chercher, et les hommes qui ont pris la source en sont la garnison.\n\nPuisez à quatre sources, et gardez-les toutes quatre ensemble deux minutes.",
    "the black road SURGES": "la route noire DÉFERLE",
    "The black road surges — Chaos redoubles!": "La route noire déferle — le Chaos redouble !",
    "the Black Tor": "le Tertre Noir",
    "the Broken Stair": "l'Escalier Brisé",
    "The Butts": "Les Buttes de tir",
    "The campaign": "La campagne",
    "the centre": "plein centre",
    "the chains hold {v}s": "les chaînes tiennent {v} s",
    "the Champion you called through the Trump": "le Champion appelé par l'Atout",
    "The chapter is lost. {title} waits again.": "Le chapitre est perdu. {title} vous attend de nouveau.",
    "The city is YOURS": "La cité est À VOUS",
    "the City of {name}": "la Cité de {name}",
    "the Cold Cistern": "la Citerne Froide",
    "THE COURTS": "LES COURS",
    "the Deep Font": "la Fontaine Profonde",
    "the Drowned Bell": "la Cloche Noyée",
    "The enemy": "L’ennemi",
    "the enemy": "l'ennemi",
    "the enemy banner": "la bannière ennemie",
    "the enemy stands there": "l'ennemi s'y tient",
    "The family champion, called through a Trump. One at a time, and worth an army while he stands.": "Le champion de la famille, appelé par un Atout. Un seul à la fois, et il vaut une armée tant qu'il tient debout.",
    "The far side becomes the sheltered one. Your men fall back through it and take cover on the other face.": "Le côté opposé devient le côté abrité. Vos hommes repassent au travers et se mettent à couvert sur l'autre face.",
    "The garrison you can afford. He lines a curtain and fills a tower — and an arrow has never brought down a wall.": "La garnison que vous pouvez vous offrir. Il borde une courtine et garnit une tour — et jamais une flèche n'a abattu un mur.",
    "the gentlest": "le plus clément",
    "the Glass Rill": "le Ru de Verre",
    "the Green Well": "le Puits Vert",
    "the Grey Crag": "le Roc Gris",
    "The ground is contested": "Le terrain est disputé",
    "The ground will not bear it": "Le sol ne le supportera pas",
    "the ground will not bear it — wood, rock or water": "le sol ne le portera pas — bois, roc ou eau",
    "The Gun Pit": "La Fosse à Canons",
    "the hardest": "le plus redoutable",
    "The heir the other heirs face — no lapses, and he comes almost at once.": "L'héritier que les autres héritiers affrontent — sans défaillance, et il vient presque aussitôt.",
    "the High Shoulder": "la Haute Épaule",
    "The house guard. Two soldiers out-fight him and neither of them lives through a storm.": "La garde de la maison. Deux soldats le surpassent, et aucun des deux ne survit à une tempête.",
    "THE LAN TABLE": "LA TABLE LAN",
    "The lines will not let go. Only the Pattern finished — or this Shrine thrown down — ends the walk.": "Les lignes ne lâchent pas prise. Seule la Marelle achevée — ou ce Sanctuaire abattu — met fin à la marche.",
    "The link could not be made": "Le lien n’a pu être établi",
    "the link could not be made — see below": "le lien n’a pu être établi — voir ci-dessous",
    "The link has gone quiet — waiting for the host": "Le lien s’est tu — en attente de l’hôte",
    "The link is back": "Le lien est revenu",
    "The link to the host is gone — the match is ended": "Le lien avec l’hôte est perdu — la partie est terminée",
    "The link to the host is severed — the match is ended": "Le lien avec l’hôte est tranché — la partie est terminée",
    "The masons are already in it": "Les maçons y sont déjà",
    "the masons are already in it": "les maçons y sont déjà",
    "The Master of Arms broke on your stone. A wall is an army that never tires.": "Le Maître d'Armes s'est brisé sur votre pierre. Un mur est une armée qui ne se lasse jamais.",
    "The Master of Arms: quickest to act, hardest to mislead, and the strongest heir the referee can find. Nothing about him is a handicap.": "Le Maître d'Armes : le plus prompt à agir, le plus difficile à tromper, et le plus fort héritier que l'arbitre puisse trouver. Rien en lui n'est un handicap.",
    "The match is decided": "La partie est jouée",
    "the Mirror Pool": "le Bassin-Miroir",
    "THE MUSTER ROLL": "LE RÔLE DES TROUPES",
    "the Old Barrow": "le Vieux Tumulus",
    "The old war is lost to a new age — a new one begins": "L’ancienne guerre s’est perdue dans un âge nouveau — une autre commence",
    "The order was refused: {err}": "L’ordre a été refusé : {err}",
    "THE OTHER CHAPTERS": "LES AUTRES CHAPITRES",
    "The Outriders": "Les Éclaireurs",
    "THE PATTERN": "LA MARELLE",
    "The Pattern holds, and it answers to your name.": "La Marelle tient, et elle répond à votre nom.",
    "The Pattern is what it is — there is nothing to raise": "La Marelle est ce qu’elle est — il n’y a rien à élever",
    "The Ram Shed": "La Remise aux Béliers",
    "the Raven Steps": "les Marches du Corbeau",
    "the reach war": "la guerre des marches",
    "the Reach War": "la Guerre des Marches",
    "The reach war": "La Guerre des Marches",
    "THE REACH WAR": "LA GUERRE DES MARCHES",
    "the reach war in your pocket, dealt to this table": "la guerre des marches de votre poche, distribuée à cette table",
    "the reach war · LAN {n}-way": "la guerre des marches · LAN à {n}",
    "the reach war: a new country, sixteen thrones, one Pattern": "la guerre des marches : un pays neuf, seize trônes, une seule Marelle",
    "The realm valve and {n} halted standard — everything pays for troops again": "La vanne du royaume et {n} étendard arrêté — tout paie de nouveau pour des troupes",
    "The realm valve and {n} halted standards — everything pays for troops again": "La vanne du royaume et {n} étendards arrêtés — tout paie de nouveau pour des troupes",
    "the Recall — every standard struck": "le Rappel — tous les étendards abattus",
    "The rival Seat of Power lies in ruin along the black road.": "Le Siège de Pouvoir rival gît en ruine le long de la route noire.",
    "the rival’s": "au rival",
    "the Salt Spring": "la Source Salée",
    "THE SEAT": "LE SIÈGE",
    "The Shieldwall": "Le Mur de boucliers",
    "the Silver Tarn": "l'Étang d'Argent",
    "the Singing Spring": "la Source Chantante",
    "the Still Water": "l'Eau Dormante",
    "THE SUCCESSION": "LA SUCCESSION",
    "THE SUCCESSION IS YOURS": "LA SUCCESSION EST VÔTRE",
    "THE SUCCESSION PASSES YOU BY": "LA SUCCESSION VOUS ÉCHAPPE",
    "the Sunken Basin": "le Bassin Englouti",
    "the table could not be dealt: {err}": "la table n’a pu être distribuée : {err}",
    "THE THRONE IS YOURS": "LE TRÔNE EST À VOUS",
    "The Trump link is gone — pair again from the menu": "Le lien de l’Atout est rompu — appairez-vous de nouveau depuis le menu",
    "The Trump link is severed": "Le lien de l’Atout est tranché",
    "the Trumps touch…": "les Atouts se touchent…",
    "The two phones are on DIFFERENT networks": "Les deux téléphones sont sur des réseaux DIFFÉRENTS",
    "The two phones completed the handshake and then could not reach each other. <b>Check both are on the same Wi-Fi — or make this phone a hotspot and have the other join it.</b>": "Les deux téléphones ont achevé la poignée de main, puis n’ont pas pu se joindre. <b>Vérifiez qu’ils sont sur le même Wi-Fi — ou faites de ce téléphone un point d’accès et faites-y connecter l’autre.</b>",
    "THE WALK": "LA MARCHE",
    "THE WAR COUNCIL": "LE CONSEIL DE GUERRE",
    "The war council": "Le Conseil de guerre",
    "The war council — something is waiting on you": "Le Conseil de guerre — quelque chose vous attend",
    "THE WAR IN YOUR POCKET": "LA GUERRE DANS VOTRE POCHE",
    "The war is the host’s to keep — pair again and it stands where it stood": "La guerre reste chez l’hôte — appairez-vous de nouveau et elle reprendra où elle en était",
    "The Warden's Art": "L'Art du Gardien",
    "The Warden's art: he mends the man beside him. Nothing else in Amber heals, which is what makes him worth the essence.": "L'art du Gardien : il soigne l'homme à ses côtés. Rien d'autre en Ambre ne guérit, et c'est pourquoi il vaut son prix en essence.",
    "the Watcher’s Tor": "le Tertre du Guetteur",
    "the Weeping Well": "le Puits qui Pleure",
    "The wells of Shadow answer to you, and Bleys of the Flame has learned what his word is worth to a brother who was counting.": "Les puits de l'Ombre vous répondent, et Bleys de la Flamme a appris ce que vaut sa parole auprès d'un frère qui comptait.",
    "the Whispering Font": "la Fontaine qui Murmure",
    "the Wind Scarp": "l'Escarpement du Vent",
    "the work itself": "l'ouvrage lui-même",
    "The world is halted — lift it to give orders": "Le monde est en halte — levez-la pour donner des ordres",
    "Their addresses have nothing in common — one may be on mobile data, or on a guest network. <b>Put both on the same Wi-Fi, or make this phone a hotspot and have the other join it.</b>": "Leurs adresses n’ont rien en commun — l’un est peut-être sur les données mobiles, ou sur un réseau invité. <b>Mettez-les tous deux sur le même Wi-Fi, ou faites de ce téléphone un point d’accès et faites-y connecter l’autre.</b>",
    "There are no terms to be had in this war": "Il n’y a pas de trêve possible dans cette guerre",
    "There is no such heir to treat with": "Il n’existe pas d’héritier de ce nom avec qui traiter",
    "There is nothing broken to mend": "Il n’y a rien de brisé à réparer",
    "there is nothing broken to mend": "il n'y a rien de brisé à réparer",
    "There is nothing left of it to throw down": "Il n’en reste rien à abattre",
    "There is one Pattern, and it is not here — take the city that holds it": "Il n’y a qu’une Marelle, et elle n’est pas ici — prenez la cité qui la détient",
    "They are on the same network and it is refusing to carry traffic between its own devices — guest Wi-Fi and a good many home routers do this. Nothing on either phone can change it from here. <b>Make THIS phone a hotspot, join it from the other, and pair again.</b> A hotspot is a network of two with nothing in the way.": "Ils sont sur le même réseau, et celui-ci refuse de faire passer le trafic entre ses propres appareils — les Wi-Fi invités et bon nombre de box domestiques font cela. Rien, sur l’un ou l’autre téléphone, ne peut y changer quoi que ce soit d’ici. <b>Faites de CE téléphone un point d’accès, connectez-y l’autre, et appairez-vous de nouveau.</b> Un point d’accès est un réseau à deux, sans rien entre eux.",
    "this browser can’t scan QR codes": "ce navigateur ne sait pas scanner les codes QR",
    "This device has no working WebGL, which Amber needs to draw the world.<br>Try another browser, or turn on hardware acceleration.": "Cet appareil n’a pas de WebGL fonctionnel, dont Ambre a besoin pour dessiner le monde.<br>Essayez un autre navigateur, ou activez l’accélération matérielle.",
    "This phone has no local network address": "Ce téléphone n’a aucune adresse sur le réseau local",
    "This phone is on mobile data, not Wi-Fi": "Ce téléphone est sur les données mobiles, pas en Wi-Fi",
    "This Wi-Fi will not pass the two phones to each other": "Ce Wi-Fi refuse de relier les deux téléphones entre eux",
    "Three springs answer to you. A realm begins as a road between wells.": "Trois sources vous répondent. Un royaume commence par une route entre des puits.",
    "Throw down every {work} he has taken out in Shadow": "Abattez chaque {work} qui lui appartient au loin dans l'Ombre",
    "Throw down his {works} out in Shadow — {left} still stand": "Abattez ses {works} au loin dans l'Ombre — encore {left} debout",
    "Throw down his {works} out in Shadow — {left} still stands": "Abattez ses {works} au loin dans l'Ombre — encore {left} debout",
    "Throw it down": "L'abattre",
    "thrown down — nothing left of it": "abattue — il n’en reste rien",
    "throws chains": "lance des chaînes",
    "throws chains out to {r}": "lance des chaînes jusqu'à {r}",
    "TO ARMS — {court}": "AUX ARMES — {court}",
    "TO ARMS — {n} lord marches to {court}": "AUX ARMES — {n} seigneur marche sur {court}",
    "TO ARMS — {n} lords march to {court}": "AUX ARMES — {n} seigneurs marchent sur {court}",
    "TO ARMS: {name}": "AUX ARMES : {name}",
    "Too close to another work": "Trop près d’un autre ouvrage",
    "too close to another work": "trop près d'un autre ouvrage",
    "Too close to the court — a curtain stands outside the city circle": "Trop près de la cour — une courtine se dresse hors du cercle de la cité",
    "Too long for the crews you have — hold more Gates, or draw a shorter run": "Trop long pour vos équipes — tenez plus de Portes, ou tracez un pan plus court",
    "Too short a run to be a wall": "Un pan trop court pour faire une courtine",
    "too short a run to be a wall": "pan trop court pour faire un mur",
    "Trump of Benedict": "Atout de Benedict",
    "TRY THE CHAPTER AGAIN": "REJOUER LE CHAPITRE",
    "Turn the Spire to one art.": "Vouer la Flèche à un seul art.",
    "Turn the wall about": "Retourner le mur",
    "Two phones can only find each other on one network. <b>Join a Wi-Fi network — or make THIS phone a hotspot and have the other join it.</b>": "Deux téléphones ne peuvent se trouver que sur un même réseau. <b>Rejoignez un réseau Wi-Fi — ou faites de CE téléphone un point d’accès et faites-y connecter l’autre.</b>",
    "TWO SIDES": "DEUX CAMPS",
    "Two to four heirs, one Wi-Fi, paired by QR.": "De deux à quatre héritiers, un seul Wi-Fi, appariés par QR.",
    "unclaimed": "sans maître",
    "unexplored": "inexploré",
    "Until it is finished it earns nothing and holds no ground, and your masons can start nothing else.": "Tant qu'il n'est pas achevé, il ne rapporte rien et ne tient aucun terrain, et vos maçons ne peuvent rien entreprendre d'autre.",
    "upgrade ?{br}": "améliorer ?{br}",
    "Upgrade to level {l}": "Améliorer au niveau {l}",
    "upgrade {bt} → L{lv}{br}": "améliorer : {name} ({bt}) → N{lv}{br}",
    "V · The Pattern": "V · La Marelle",
    "V · THE PATTERN": "V · LA MARELLE",
    "Veteran ": "Vétéran ",
    "Veteran {name}": "{name} vétéran",
    "VI · The Truce": "VI · La Trêve",
    "VI · THE TRUCE": "VI · LA TRÊVE",
    "VII · The Throne": "VII · Le Trône",
    "VII · THE THRONE": "VII · LE TRÔNE",
    "Walk it again, from the first chapter": "Reprendre le chemin, depuis le premier chapitre",
    "Walk the Pattern to its heart": "Parcourez la Marelle jusqu'en son cœur",
    "Walk the Pattern — {p}%": "Parcourez la Marelle — {p} %",
    "war": "guerre",
    "Warden": "Gardien",
    "WARDEN": "GARDIEN",
    "warden": "gardien",
    "warden by default": "gardien par défaut",
    "Wardens": "Gardiens",
    "Watchtower": "Tour de guet",
    "Watchtowers": "Tours de guet",
    "works": "ouvrage",
    "WORKS": "OUVRAGES",
    "WORKS LOST": "OUVRAGES PERDUS",
    "YIELDED — hold the court and it swears": "CÉDÉE — tenez la cour et elle prêtera serment",
    "YIELDED — HOLD THE COURT TO CLAIM": "CÉDÉE — TENEZ LA COUR POUR LA REVENDIQUER",
    "You": "Vous",
    "YOU": "VOUS",
    "you and {n} heir": "vous et {n} héritier",
    "you and {n} heirs": "vous et {n} héritiers",
    "You are out of the fight — you watch now": "Vous êtes hors du combat — vous regardez désormais",
    "YOU break with {b}": "VOUS rompez avec {b}",
    "you called it": "vous l'avez ordonnée",
    "You cannot storm what you cannot see": "Vous ne pouvez déchaîner la tempête sur ce que vous ne voyez pas",
    "You command from {court} — its purse is your purse": "Vous commandez depuis {court} — sa bourse est votre bourse",
    "you have one already": "vous en avez déjà un",
    "You have set foot upon the Pattern!": "Vous avez posé le pied sur la Marelle !",
    "You have walked the Pattern to its blazing heart and spoken your name.": "Vous avez parcouru la Marelle jusqu’à son cœur ardent et prononcé votre nom.",
    "You is three quarters of the way round the Pattern": "Vous avez accompli les trois quarts de la Marelle",
    "you is three quarters of the way round the Pattern": "vous avez accompli les trois quarts de la Marelle",
    "You nears the final veil of the Pattern!": "Vous approchez du dernier voile de la Marelle !",
    "you nears the final veil of the Pattern!": "vous approchez du dernier voile de la Marelle !",
    "you raze a rival {nm}": "vous rasez un ouvrage rival : {nm}",
    "You raze the rival’s works": "Vous rasez les ouvrages du rival",
    "you set foot upon the Pattern": "vous posez le pied sur la Marelle",
    "you set foot upon the Pattern!": "vous posez le pied sur la Marelle !",
    "you throw down your own {nm}": "vous abattez votre propre ouvrage : {nm}",
    "You throw the city down — it will be nobody’s now": "Vous abattez la cité — elle ne sera plus à personne",
    "You walked it to its blazing heart and spoke your name. The universe rearranges.": "Vous l'avez parcourue jusqu'à son cœur flamboyant et vous avez prononcé votre nom. L'univers se réordonne.",
    "You walks the Pattern — halfway to the throne": "Vous parcourez la Marelle — à mi-chemin du trône",
    "you walks the Pattern — halfway to the throne": "vous parcourez la Marelle — à mi-chemin du trône",
    "you, alone": "vous, seul",
    "your ally": "votre allié",
    "your ally — his own counsel": "votre allié — il suit son propre conseil",
    "Your champion already walks the board": "Votre champion foule déjà le terrain",
    "your court": "votre cour",
    "YOUR DEAD": "VOS MORTS",
    "YOUR DEAD: {dead} — {foe} to the heirs, {chaos} to Chaos": "VOS MORTS : {dead} — {foe} par les héritiers, {chaos} par le Chaos",
    "Your footing — how hard the heirs play": "Votre rang — la rigueur avec laquelle jouent les héritiers",
    "your masons are all at work — every Shadow Gate you hold hires another crew": "vos maçons sont tous à l'ouvrage — chaque Porte d'Ombre que vous tenez engage une équipe de plus",
    "Your masons are all at work — hold more Gates to hire another crew": "Vos maçons sont tous à l’ouvrage — tenez plus de Portes pour engager une autre équipe",
    "your offer stands — tap to withdraw": "votre offre tient — touchez pour la retirer",
    "your own banner": "votre propre bannière",
    "your own hand": "votre propre main",
    "your peak: {army} troops, {works} works · works lost {lost}, razed {razed}": "votre apogée : {army} soldats, {works} ouvrages · ouvrages perdus {lost}, rasés {razed}",
    "Your Seat of Power lies in ruin. The road took it.": "Votre Siège de Pouvoir gît en ruine. La route l’a emporté.",
    "YOUR Shrine is thrown down — {n}% left": "VOTRE Sanctuaire est abattu — il restait {n} %",
    "YOUR SIDE": "VOTRE CAMP",
    "Your war waits where you put it down — one tap resumes it.": "Votre guerre attend là où vous l'avez laissée — une touche la reprend.",
    "YOUR WAR — {n} HEIRS": "VOTRE GUERRE — {n} HÉRITIERS",
    "Your works are under attack!": "On attaque vos ouvrages !",
    "YOUR {nm} is razed{hand}": "RASÉ : votre {nm}{hand}",
    "Your {what} is under attack!": "On attaque votre {what} !",
    "Your {work} has been RAZED!": "On a RASÉ votre {work} !",
    "yours": "à vous",
    "{a} and {b} come to terms": "{a} et {b} concluent une trêve",
    "{a} BREAKS the truce": "{a} ROMPT la trêve",
    "{a} breaks with {b}": "{a} rompt avec {b}",
    "{a} of {b}": "{a} sur {b}",
    "{a} v {b} — {c} contenders, {m} minor lords": "{a} contre {b} — {c} prétendants, {m} seigneurs mineurs",
    "{a} v {b} — {n} contenders": "{a} contre {b} — {n} prétendants",
    "{cl} of {n}": "{cl} sur {n}",
    "{d} blow · {r} range · musters nobody": "coup {d} · portée {r} · ne lève personne",
    "{d} dmg · {dps}/s · {r} range": "{d} dégâts · {dps}/s · portée {r}",
    "{held} — the Pattern lies in {at}": "{held} — la Marelle repose en {at}",
    "{held} — {at} is yours: raise a Shrine and walk": "{held} — {at} est à vous : élevez un Sanctuaire et parcourez la Marelle",
    "{hint} Choose once — the choice does not come again.": "{hint} Choisissez une fois — le choix ne se représentera pas.",
    "{hp} hp · {d} blow": "{hp} PV · coup {d}",
    "{hp} hp · {d} blow · {r} reach": "{hp} PV · coup {d} · allonge {r}",
    "{icon} {name} — level {l}": "{icon} {name} — niveau {l}",
    "{icon} {name} — under which standard?": "{icon} {name} — sous quel étendard ?",
    "{len} — the masons reach {reach}": "{len} — les maçons portent jusqu’à {reach}",
    "{len} — too short": "{len} — trop court",
    "{mine} of {all} cities held": "Cités tenues : {mine} sur {all}",
    "{mine} of {all} city held": "Cité tenue : {mine} sur {all}",
    "{name} has set foot upon the Pattern!": "{name} a posé le pied sur la Marelle !",
    "{name} is three quarters of the way round the Pattern": "{name} a accompli les trois quarts de la Marelle",
    "{name} nears the final veil of the Pattern!": "{name} approche du dernier voile de la Marelle !",
    "{name} walks the Pattern — halfway to the throne": "{name} parcourt la Marelle — à mi-chemin du trône",
    "{name} · level {l}": "{name} · niveau {l}",
    "{name}, level 1": "{name}, niveau 1",
    "{name}, level 1 — mustered from the first": "{name}, niveau 1 — levé dès le départ",
    "{name}, level {l} — chosen once, and forever": "{name}, niveau {l} — choisi une fois, et pour toujours",
    "{name}’s": "à {name}",
    "{name}’s Seat": "Siège de {name}",
    "{n} ({p}% Chaos)": "{n} ({p} % Chaos)",
    "{n} banners — {n} contenders, every one for himself": "{n} bannières — {n} prétendants, chacun pour soi",
    "{n} blow": "coup {n}",
    "{n} cities": "{n} cités",
    "{n} city": "{n} cité",
    "{n} crew": "{n} équipe",
    "{n} crews": "{n} équipes",
    "{n} hall": "{n} caserne",
    "{n} hall musters under it": "{n} caserne lève sous lui",
    "{n} hall, mustering nobody": "{n} caserne, ne levant personne",
    "{n} halls": "{n} casernes",
    "{n} halls muster under it": "{n} casernes lèvent sous lui",
    "{n} halls, mustering nobody": "{n} casernes, ne levant personne",
    "{n} halted standard pays for troops again": "{n} étendard arrêté paie de nouveau pour des troupes",
    "{n} halted standards pay for troops again": "{n} étendards arrêtés paient de nouveau pour des troupes",
    "{n} heir, each his own banner": "{n} héritier, chacun sous sa bannière",
    "{n} heir, one banner": "{n} héritier, une bannière",
    "{n} HEIRS CONTEND": "{n} HÉRITIERS S’AFFRONTENT",
    "{n} heirs, each his own banner": "{n} héritiers, chacun sous sa bannière",
    "{n} heirs, one banner": "{n} héritiers, une bannière",
    "{n} hp": "{n} PV",
    "{n} men": "{n} hommes",
    "{n} of {max} seated — add another, or begin": "{n} sur {max} attablés — ajoutez-en un, ou commencez",
    "{n} pace": "allure {n}",
    "{n} reach": "allonge {n}",
    "{n} to a hall": "{n} par caserne",
    "{n} · razed {r}": "{n} · rasés {r}",
    "{tag} · {name} at level {l}, chosen once and forever": "{tag} · {name} au niveau {l}, choisi une fois et pour toujours",
    "{who} agrees to terms": "{who} accepte la trêve",
    "{who} asks for terms": "{who} demande une trêve",
    "{who} BREAKS the truce!": "{who} ROMPT la trêve !",
    "{who} calls down the storm!": "{who} appelle la tempête !",
    "{who} draws a Trump!": "{who} tire un Atout !",
    "{who} has left the table — a shadow of him fights on": "{who} a quitté la table — une ombre de lui poursuit le combat",
    "{who} has left the table — the match is ended": "{who} a quitté la table — la partie est terminée",
    "{who} has walked the Pattern to its heart. The universe rearranges.": "{who} a parcouru la Marelle jusqu’en son cœur. L’univers se réordonne.",
    "{who} is at your {what}": "{who} est à votre ouvrage : {what}",
    "{who} is at your {what}!": "{who} est à votre {what} !",
    "{who} is inside your city": "{who} est dans votre cité",
    "{who} is inside your city!": "{who} est dans votre cité !",
    "{who} is three quarters of the way round the Pattern": "{who} a accompli les trois quarts de la Marelle",
    "{who} is toppled": "{who} est renversé",
    "{who} is torn off the Pattern — {n}% left": "{who} est arraché à la Marelle — il restait {n} %",
    "{who} nears the final veil of the Pattern!": "{who} approche du dernier voile de la Marelle !",
    "{who} set foot upon the Pattern!": "{who} pose le pied sur la Marelle !",
    "{who} sets foot upon the Pattern": "{who} pose le pied sur la Marelle",
    "{who} swears to you — his city, his purse and his men are yours": "{who} vous prête serment — sa cité, sa bourse et ses hommes sont à vous",
    "{who} takes the city": "{who} prend la cité",
    "{who} throws the city down": "{who} abat la cité",
    "{who} walks the Pattern — halfway to the throne": "{who} parcourt la Marelle — à mi-chemin du trône",
    "{who}’s Seat has yielded — its court is open to anyone who can hold it": "Le Siège de {who} a cédé — sa cour est ouverte à quiconque saura la tenir",
    "{who}’s Seat yields — take the court and it is yours": "Le Siège de {who} cède — prenez la cour et elle est à vous",
    "×{v} vs stone": "×{v} contre la pierre",
    "— no men": "— aucun homme",
    "— the hours — (\"+n\" works rising, \"*\" walking, chaos = fiends alive)": "— les heures — (« +n » ouvrages en chantier, « * » sur la Marelle, chaos = démons vivants)",
    "— the moments —": "— les moments —",
    "— The Succession —": "— La Succession —",
    "— your orders —": "— vos ordres —",
    "…(truncated at {n})": "…(tronqué à {n})",
    "…and takes ×{v} from every blow": "…et subit ×{v} de chaque coup",
    "−{n}◆/s muster": "−{n}◆/s de levée",
    "−{n}◆/s while walking": "−{n}◆/s pendant la marche",
    "⏸ Halt the Muster": "⏸ Arrêter la levée",
    "▶ Resume the Muster": "▶ Reprendre la levée",
    "◆ Peace is time. Spend it on the ground, not on halls you do not yet need": "◆ La paix, c'est du temps. Dépensez-le sur le terrain, non sur des casernes dont vous n'avez pas encore besoin",
    "◎ GO THERE": "◎ S'Y RENDRE",
    "⚐ No standard yet": "⚐ Pas encore d'étendard",
    "⚐ Raise a Barracks — it raises a standard of its own, and its flag joins the tray": "⚐ Élevez une caserne — elle lève son propre étendard, et son fanion rejoint la barre",
    "⚐ Send a company to the wall — archers climb it, the rest hold its foot": "⚐ Envoyez une compagnie au mur — les archers y montent, les autres tiennent son pied",
    "⚐ Standard {n}": "⚐ Étendard {n}",
    "⚐ TAP YOUR OWN TROOPS to pick up their standard, then tap where they should stand": "⚐ TOUCHEZ VOS PROPRES TROUPES pour saisir leur étendard, puis touchez l'endroit où elles doivent se tenir",
    "⚐ Two standards — one may take ground while the other fights": "⚐ Deux étendards — l'un peut prendre du terrain pendant que l'autre se bat",
    "⚑ ACCEPT TERMS": "⚑ ACCEPTER LA TRÊVE",
    "⚑ at terms — tap to break": "⚑ en trêve — touchez pour rompre",
    "⚑ BREAK TERMS": "⚑ ROMPRE LA TRÊVE",
    "⚑ OFFER TERMS": "⚑ OFFRIR UNE TRÊVE",
    "⚑ Out of Shadow": "⚑ Venus de l'Ombre",
    "⚑ TERMS STAND, top right — while they do, neither of you may strike the other": "⚑ LA TRÊVE TIENT, en haut à droite — tant qu'elle dure, nul de vous deux ne peut frapper l'autre",
    "⚑ WITHDRAW OFFER": "⚑ RETIRER L’OFFRE",
    "⚒ A Siege Works raises Rams and Bombards — they are what stone fears": "⚒ Un Atelier de siège lève Béliers et Bombardes — c'est ce que craint la pierre",
    "⚔ He can see your Shrine now — keep an army on it. Break it and the walk stops, and you lose ground you have already paid for": "⚔ Il voit votre Sanctuaire désormais — gardez une armée dessus. Qu'il soit brisé et le parcours s'arrête, et vous perdez une avance déjà payée",
    "⚔ His Gates stand on springs. Find them, and plant a standard on one": "⚔ Ses Portes se dressent sur des sources. Trouvez-les, et plantez un étendard sur l'une d'elles",
    "⚔ The Muster Roll": "⚔ Le Rôle des Troupes",
    "⚔ The truce is over — he has been mustering the whole time you were digging": "⚔ La trêve est rompue — il levait des hommes pendant tout le temps que vous creusiez",
    "⚔ TO ARMS — every lord in reach, to your court": "⚔ AUX ARMES — chaque seigneur à portée, vers votre cour",
    "⚔ To win by force, plant a standard on the rival city itself": "⚔ Pour vaincre par la force, plantez un étendard sur la cité rivale elle-même",
    "⚠ The saved war will be LOST — tap again to begin anew": "⚠ La guerre sauvegardée sera PERDUE — touchez encore pour recommencer",
    "⚠ This phone is on mobile data — join a Wi-Fi network, or make it a hotspot": "⚠ Ce téléphone est sur les données mobiles — rejoignez un réseau Wi-Fi, ou faites-en un point d’accès",
    "⚡ The Jewel calls down a storm — it is worth more on a rival than on the weather": "⚡ Le Joyau fait tomber une tempête — elle vaut davantage sur un rival que sur le temps qu'il fait",
    "✓ COPIED — PASTE IT ANYWHERE": "✓ COPIÉ — COLLEZ-LE OÙ VOUS VOULEZ",
    "✓ SAVED": "✓ ENREGISTRÉ",
    "✓ This phone is on Wi-Fi": "✓ Ce téléphone est en Wi-Fi",
    "✴ Three springs will carry the drain — raise a Pattern Shrine and step on": "✴ Trois sources porteront la saignée — élevez un Sanctuaire de la Marelle et engagez-vous",
    "✴ Walk the Pattern": "✴ Parcourir la Marelle",
    "✴ Walking the Pattern": "✴ Sur la Marelle",
    "✴ Your Shrine is thrown down — the Pattern lets go of you ({n}%)": "✴ Votre Sanctuaire est abattu — la Marelle vous lâche ({n} %)",
    "✴ {n}% of the Pattern is walked in your name": "✴ {n} % de la Marelle parcourus en votre nom",
    "✴ {p}% — paused": "✴ {p} % — à l'arrêt",
    "✴ {p}% — walking": "✴ {p} % — en marche",
    "✴ {who} is torn off the Pattern — {n}% left": "✴ {who} est arraché à la Marelle — il en restait {n} %",
    "⟲ Begin a new war": "⟲ Commencer une nouvelle guerre",
    "🌀 A company left standing on a spring is what keeps its Gate": "🌀 Une compagnie laissée sur une source, voilà ce qui garde sa Porte",
    "🎯 The throne's own guns: {dps}/s out to {r}, and no wall shades them.": "🎯 Les propres canons du trône : {dps}/s jusqu'à {r}, et nul mur ne les masque.",
    "👁 You are out of the fight — watching": "👁 Vous êtes hors du combat — vous regardez",
    "👁 You are out of the fight — watching: {who} still fight": "👁 Vous êtes hors du combat — vous regardez : {who} se battent encore",
    "👁 You are out of the fight — you watch now, with the veil lifted": "👁 Vous êtes hors du combat — vous regardez désormais, le voile levé",
    "👑 COMMAND": "👑 COMMANDER",
    "👑 Take Command Here": "👑 Prendre le commandement ici",
    "👑 Your own hand is on this court — its purse and its crews are the ones the BUILD button spends.": "👑 Votre propre main est sur cette cour — sa bourse et ses équipes sont celles que dépense le bouton BÂTIR.",
    "📜 Chronicle of the last match": "📜 Chronique de la dernière partie",
    "📜 COPY THE CHRONICLE": "📜 COPIER LA CHRONIQUE",
    "🔨 A second Gate is a second income. Keep going — three of them takes the chapter": "🔨 Une deuxième Porte, c'est un deuxième revenu. Continuez — trois d'entre elles emportent le chapitre",
    "🔨 BUILD → Curtain Wall. Tap where the run starts, then where it ends": "🔨 BÂTIR → Courtine. Touchez là où le pan commence, puis là où il finit",
    "🔨 Rising — {p}%, about {s}s more.": "🔨 En chantier — {p} %, encore {s} s environ.",
    "🔨 The masons are raising it to level {l} — {p}%, about {s}s more.": "🔨 Les maçons l'élèvent au niveau {l} — {p} %, encore {s} s environ.",
    "🔨 {name} — tap where it should stand": "🔨 {name} — touchez où l’élever",
    "🔨 {name} — tap where the run should START": "🔨 {name} — touchez où le pan doit COMMENCER",
    "🔨 {s}s of masonry — it does not shoot until they are done, and a crew of yours is on it.": "🔨 {s} s de maçonnerie — elle ne tire pas tant qu'ils n'ont pas fini, et une de vos équipes y est occupée.",
    "🔨 {s}s of masonry — it draws nothing until they are done, and a crew of yours is on it.": "🔨 {s} s de maçonnerie — elle ne puise rien tant qu'ils n'ont pas fini, et une de vos équipes y est occupée.",
    "🔨 {s}s of masonry — it musters nobody until they are done, and a crew of yours is on it.": "🔨 {s} s de maçonnerie — il ne lève personne tant qu'ils n'ont pas fini, et une de vos équipes y est occupée.",
    "🔨 {s}s of masonry — it stands idle until they are done, and a crew of yours is on it.": "🔨 {s} s de maçonnerie — il reste oisif tant qu'ils n'ont pas fini, et une de vos équipes y est occupée.",
    "🗼 Seat {hp}/{max}": "🗼 Siège {hp}/{max}",
    "🗼 YIELDED — hold the court to claim it": "🗼 CÉDÉ — tenez la cour pour le revendiquer",
    "🛡 Sound the Recall": "🛡 Sonner le Rappel"
  });
})(typeof window !== 'undefined' ? window : globalThis);
