/* proto.js — THE REACH PROTOTYPE. Not the game; a rig for one question.
 *
 * THE QUESTION. A country is one continuous land. Every city owns a REACH — a disc around it
 * that runs out past its neighbours — and a company belongs to a city and may be ordered
 * anywhere inside that city's reach and nowhere else. Does that feel like a country, and does
 * it feel like a rule or like a fence?
 *
 * WHY THE RULE IS WORTH TESTING, in one number: a flow field is a Dijkstra over its whole
 * domain. Over this land it is 70ms and 0.76MB; bounded by one city's reach it is 5.5ms and
 * 0.12MB — which is what a field costs on today's board, and it stays there however large the
 * country grows. So the rule that bounds where an army may be sent is the same rule that makes
 * a continuous world affordable. That is the whole idea, and this is it in motion.
 *
 * WHAT IS DELIBERATELY MISSING: buildings, economy, fog, walls, the Pattern, terrain cost
 * subtleties, art. Every one of them would make this prettier and none would make it answer the
 * question better. Flat 2D on purpose, so what you are looking at is the rule.
 */
(function () {
  'use strict';
  const C = window.CONST, WG = window.WorldGen, RNG = window.RNG;
  const cv = document.getElementById('c'), g = cv.getContext('2d');
  const $ = (id) => document.getElementById(id);

  /* ---------------- the shape of a country ---------------- */
  const P = {
    cities: 6,
    spacing: 900,        // city to city
    reachMul: 1.35,      // a city reaches out past its neighbours — "a bit past" is this
    cell: C.NAV.cell,
    dt: 1 / 30,
    muster: 2.0,         // seconds per man — a prototype must show the idea in a minute
    cap: 12,             // men a city keeps
    speed: 46, range: 30, aggro: 150, dmg: 9, atk: 0.9, hp: 70,
    court: 120,          // the ground you must stand on to take a city
    take: 6,             // seconds, uncontested
    cityHp: 400
  };
  const TINT = ['#ffd98a', '#ff8a96', '#c48eff', '#64d8d8', '#9fe6b0', '#ffb06a'];
  const NAME = ['Amber', 'Kolvir', 'Arden', 'Rebma', 'Begma', 'Kashfa'];

  /* ---------------- one continuous land ----------------
   * Generated by the game's own generator at COUNTRY scale. There is one land and one set of
   * coordinates; a city's reach is a window into it and never a copy of it, which is why the
   * terrain costs the same whether one city looks at it or six. */
  let land = null, cost = null, LW = 0, LH = 0, WORLD = { w: 0, h: 0 };
  let cities = [], men = [], nextId = 1, t = 0, rng = null, seed = 1;

  function build(sd) {
    seed = sd >>> 0;
    rng = RNG.make(seed);
    /* six cities: a ring of five about one, which gives every city neighbours and the middle
     * one a front on every side — the cheapest layout that is not a line */
    const R = P.spacing;
    const pts = [{ x: 0, y: 0 }];
    for (let i = 0; i < P.cities - 1; i++) {
      const a = (i / (P.cities - 1)) * Math.PI * 2;
      pts.push({ x: Math.cos(a) * R, y: Math.sin(a) * R });
    }
    const reach = P.spacing * P.reachMul, pad = reach * 1.05;
    let mnX = Infinity, mnY = Infinity, mxX = -Infinity, mxY = -Infinity;
    for (const p of pts) { mnX = Math.min(mnX, p.x); mxX = Math.max(mxX, p.x); mnY = Math.min(mnY, p.y); mxY = Math.max(mxY, p.y); }
    WORLD.w = Math.ceil((mxX - mnX + pad * 2) / P.cell) * P.cell;
    WORLD.h = Math.ceil((mxY - mnY + pad * 2) / P.cell) * P.cell;
    const keep = { w: C.MAP.W, h: C.MAP.H };
    C.MAP.W = WORLD.w; C.MAP.H = WORLD.h;
    land = WG.generate(seed);
    C.MAP.W = keep.w; C.MAP.H = keep.h;
    LW = land.W; LH = land.H;
    cost = new Uint8Array(LW * LH);
    for (let i = 0; i < LW * LH; i++) cost[i] = WG.COST[land.terra[i]] || 0;

    cities = pts.map((p, i) => ({
      id: i, name: NAME[i], owner: i,
      x: p.x + pad - mnX, y: p.y + pad - mnY,
      reach, hp: P.cityHp, maxHp: P.cityHp, cd: 0, hold: null,
      fields: new Map()                    // (goal cell) -> Float32Array, bounded by this reach
    }));
    /* EVERY CITY MUST STAND ON THE MAINLAND, and standable ground is not enough. The land is
     * noise, so a city may land in a lake — or, far worse and measured on the very first country
     * this prototype made, on an ISLAND: perfectly good ground with no path to anywhere. That
     * city could neither attack nor be attacked and simply mustered for ever, which is a player
     * who cannot play.
     * Growing its reach does not help, because there is no route at any radius. So the largest
     * connected piece of passable ground is found once, and every city is nudged into it — which
     * is what `WorldGen` itself does with its `mainland` pass, for exactly this reason. */
    mainland();
    for (const c of cities) {
      if (onMain(c.x, c.y)) continue;
      let best = null, bd = Infinity;
      for (let r = P.cell; r < 1400 && !best; r += P.cell)
        for (let a = 0; a < 24; a++) {
          const x = c.x + Math.cos(a / 24 * Math.PI * 2) * r, y = c.y + Math.sin(a / 24 * Math.PI * 2) * r;
          if (onMain(x, y) && r < bd) { bd = r; best = { x, y }; }
        }
      if (best) { c.x = best.x; c.y = best.y; }
    }
    /* WHOM YOU CAN ACTUALLY GET TO, computed from a real search and never from distance: two
     * cities a thousand apart with a lake between them are not neighbours, and the player can
     * see the lake. This is the honest version of a "closed border". */
    const linkUp = () => {
      for (const c of cities) {
        const f = fieldFor(c, c.x, c.y);
        c.nbrs = cities.filter((o) => o !== c && inReach(c, o.x, o.y) && isFinite(at(f, o.x, o.y))).map((o) => o.id);
      }
    };
    linkUp();
    /* AND A CITY WITH NO NEIGHBOURS IS A PLAYER WHO CANNOT PLAY. Measured on the first land this
     * prototype generated: one of the six sat behind a lake and its reach could path to nothing,
     * so it could neither attack nor be attacked and simply mustered for ever.
     * It is the sharp edge of the whole idea, and the honest fix is not to move the city — it is
     * to let its reach GROW until it can see somebody. A city on poor ground commands further,
     * which reads as a real thing rather than as a repair. */
    for (let pass = 0; pass < 6; pass++) {
      const cut = cities.filter((c) => !c.nbrs.length);
      if (!cut.length) break;
      for (const c of cut) { c.reach *= 1.18; c.fields.clear(); }
      linkUp();
    }
    men = []; nextId = 1; t = 0;
    for (const c of cities) for (let k = 0; k < 4; k++) spawn(c);
    picked = 0;
    home();
  }

  /* the largest connected piece of passable ground — one flood fill, once per land */
  let main = null;
  function mainland() {
    const seen = new Uint8Array(LW * LH);
    main = new Uint8Array(LW * LH);
    let bestN = 0;
    for (let start = 0; start < LW * LH; start++) {
      if (seen[start] || !cost[start]) continue;
      const comp = [start], q = [start];
      seen[start] = 1;
      while (q.length) {
        const cur = q.pop(), cx = cur % LW, cy = (cur - cx) / LW;
        for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
          const nx = cx + dx, ny = cy + dy;
          if (nx < 0 || ny < 0 || nx >= LW || ny >= LH) continue;
          const ni = ny * LW + nx;
          if (seen[ni] || !cost[ni]) continue;
          seen[ni] = 1; comp.push(ni); q.push(ni);
        }
      }
      if (comp.length > bestN) { bestN = comp.length; main.fill(0); for (const i of comp) main[i] = 1; }
    }
  }
  const onMain = (x, y) => { const i = cellOf(x, y); return i >= 0 && main && main[i] === 1; };

  const cellOf = (x, y) => {
    const cx = Math.floor(x / P.cell), cy = Math.floor(y / P.cell);
    if (cx < 0 || cy < 0 || cx >= LW || cy >= LH) return -1;
    return cy * LW + cx;
  };
  const standable = (x, y) => { const i = cellOf(x, y); return i >= 0 && cost[i] > 0; };
  const inReach = (c, x, y) => (x - c.x) * (x - c.x) + (y - c.y) * (y - c.y) < c.reach * c.reach;
  const at = (f, x, y) => { const i = cellOf(x, y); return i < 0 ? Infinity : f[i]; };

  /* ---------------- A FLOW FIELD, BOUNDED BY THE CITY'S REACH ----------------
   * The one piece of real machinery here, and the reason the design works. The land is one
   * array; the search is what is bounded. Cached per city, because a company's orders are all
   * inside its own city's reach and so all its fields are too. */
  const SQ2 = Math.SQRT2;
  let builtFields = 0;
  function fieldFor(c, gx, gy) {
    const goal = cellOf(gx, gy);
    if (goal < 0) return null;
    const had = c.fields.get(goal);
    if (had) return had;
    if (c.fields.size > 24) c.fields.clear();
    builtFields++;
    const n = LW * LH, dist = new Float32Array(n).fill(Infinity);
    const hi = new Int32Array(n + 1), hd = new Float32Array(n + 1);
    let hn = 0;
    const push = (i, d) => { let k = ++hn; hi[k] = i; hd[k] = d;
      while (k > 1) { const p = k >> 1; if (hd[p] <= hd[k]) break;
        const ti = hi[p], td = hd[p]; hi[p] = hi[k]; hd[p] = hd[k]; hi[k] = ti; hd[k] = td; k = p; } };
    const pop = () => { const top = hi[1]; hi[1] = hi[hn]; hd[1] = hd[hn]; hn--;
      let k = 1; for (;;) { const l = k << 1, r = l + 1; let s = k;
        if (l <= hn && hd[l] < hd[s]) s = l; if (r <= hn && hd[r] < hd[s]) s = r;
        if (s === k) break; const ti = hi[s], td = hd[s]; hi[s] = hi[k]; hd[s] = hd[k]; hi[k] = ti; hd[k] = td; k = s; } return top; };
    const R2 = c.reach * c.reach;
    dist[goal] = 0; push(goal, 0);
    while (hn > 0) {
      const cur = pop(), cd = dist[cur], cx = cur % LW, cy = (cur - cx) / LW;
      for (let dy = -1; dy <= 1; dy++) { const ny = cy + dy; if (ny < 0 || ny >= LH) continue;
        for (let dx = -1; dx <= 1; dx++) { if (!dx && !dy) continue;
          const nx = cx + dx; if (nx < 0 || nx >= LW) continue;
          const wx = (nx + 0.5) * P.cell - c.x, wy = (ny + 0.5) * P.cell - c.y;
          if (wx * wx + wy * wy > R2) continue;            // THE REACH, and the whole idea
          const cc = cost[ny * LW + nx]; if (cc === 0) continue;
          const nd = cd + cc * (dx && dy ? SQ2 : 1), ni = ny * LW + nx;
          if (nd < dist[ni]) { dist[ni] = nd; push(ni, nd); } } } }
    c.fields.set(goal, dist);
    return dist;
  }
  /* downhill, sampled from the four cells around him so a column does not march in eight
   * headings — the same rule the game's own steering uses */
  function steer(f, x, y) {
    const here = cellOf(x, y);
    if (here < 0 || !isFinite(f[here])) return null;
    let bd = f[here], bi = -1;
    const cx = here % LW, cy = (here - cx) / LW;
    for (let dy = -1; dy <= 1; dy++) { const ny = cy + dy; if (ny < 0 || ny >= LH) continue;
      for (let dx = -1; dx <= 1; dx++) { if (!dx && !dy) continue;
        const nx = cx + dx; if (nx < 0 || nx >= LW) continue;
        const ni = ny * LW + nx; if (f[ni] < bd) { bd = f[ni]; bi = ni; } } }
    if (bi < 0) return null;
    const bx = bi % LW, by = (bi - bx) / LW;
    const vx = bx - cx, vy = by - cy, L = Math.hypot(vx, vy) || 1;
    return { x: vx / L, y: vy / L };
  }

  /* ---------------- men ---------------- */
  function spawn(c) {
    const a = rng.next() * Math.PI * 2, r = 40 + rng.next() * 50;
    men.push({ id: nextId++, city: c.id, owner: c.owner, x: c.x + Math.cos(a) * r, y: c.y + Math.sin(a) * r,
               hp: P.hp, cd: 0 });
  }
  /* A COMPANY BELONGS TO A CITY, and its order is the city's — so taking a city takes its men
   * and its reach in one act, which is the strategic point of the whole rule. */
  function orderOf(c) { return c.order || { x: c.x, y: c.y }; }

  function step() {
    t += P.dt;
    /* muster */
    for (const c of cities) {
      if (c.owner < 0) continue;
      c.cd -= P.dt;
      if (c.cd <= 0) { c.cd = P.muster;
        if (men.filter((m) => m.city === c.id && m.hp > 0).length < P.cap) spawn(c); }
    }
    /* fight, then march */
    for (const m of men) {
      if (m.hp <= 0) continue;
      m.cd -= P.dt;
      let foe = null, fd = P.aggro * P.aggro;
      for (const o of men) {
        if (o.hp <= 0 || o.owner === m.owner) continue;
        const d = (o.x - m.x) ** 2 + (o.y - m.y) ** 2;
        if (d < fd) { fd = d; foe = o; }
      }
      if (foe) {
        const d = Math.sqrt(fd);
        if (d <= P.range) { if (m.cd <= 0) { foe.hp -= P.dmg; m.cd = P.atk; } continue; }
        const mv = P.speed * P.dt / d;
        const nx = m.x + (foe.x - m.x) * mv, ny = m.y + (foe.y - m.y) * mv;
        if (standable(nx, ny)) { m.x = nx; m.y = ny; }
        continue;
      }
      const c = cities[m.city];
      const ord = orderOf(c);
      const f = fieldFor(c, ord.x, ord.y);
      if (!f) continue;
      if ((m.x - ord.x) ** 2 + (m.y - ord.y) ** 2 < 44 * 44) continue;
      const s = steer(f, m.x, m.y);
      if (!s) continue;
      const nx = m.x + s.x * P.speed * P.dt, ny = m.y + s.y * P.speed * P.dt;
      if (standable(nx, ny)) { m.x = nx; m.y = ny; }
    }
    /* a court is broken by standing in it, and then TAKEN by standing in it — the same verb the
     * game uses for a spring, and the reason a raid is not a conquest */
    for (const c of cities) {
      const near = men.filter((m) => m.hp > 0 && (m.x - c.x) ** 2 + (m.y - c.y) ** 2 < P.court * P.court);
      const owners = new Set(near.map((m) => m.owner));
      const foes = near.filter((m) => m.owner !== c.owner);
      if (c.owner >= 0 && foes.length) c.hp -= foes.length * 9 * P.dt;
      if (c.owner >= 0 && c.hp <= 0) {                 // it yields: nobody's until somebody holds it
        c.hp = 0; c.owner = -1; c.order = null; c.hold = null;
        for (const m of men) if (m.city === c.id) { m.hp = 0; }
        say(c.name + ' has yielded');
      }
      if (c.owner < 0) {
        const claim = owners.size === 1 ? near[0].owner : -1;
        if (claim < 0) { c.hold = null; continue; }
        if (!c.hold || c.hold.by !== claim) c.hold = { by: claim, since: t };
        if (t - c.hold.since >= P.take) {
          /* it comes back HURT, exactly as a taken Seat does in the game */
          c.owner = claim; c.hp = c.maxHp * 0.4; c.hold = null; c.order = null;
          say(c.name + (claim === 0 ? ' is yours — and so is its reach' : ' falls to ' + NAME[claim]));
        }
      }
    }
    men = men.filter((m) => m.hp > 0);
    /* the bots: march on the nearest city they can actually get to that is not theirs */
    if (Math.floor(t * 2) !== Math.floor((t - P.dt) * 2)) {
      for (const c of cities) {
        if (c.owner <= 0) continue;                    // 0 is you; -1 is nobody
        const mine = men.filter((m) => m.city === c.id).length;
        const tgt = c.nbrs.map((i) => cities[i]).filter((o) => o.owner !== c.owner)
          .sort((a, b) => (a.x - c.x) ** 2 + (a.y - c.y) ** 2 - ((b.x - c.x) ** 2 + (b.y - c.y) ** 2))[0];
        /* a bot marches once it has a company worth marching, and holds otherwise */
        c.order = (tgt && mine >= P.cap - 4) ? { x: tgt.x, y: tgt.y } : { x: c.x, y: c.y };
      }
    }
  }

  /* ---------------- the view ---------------- */
  let cam = { x: 0, y: 0, z: 0.22 }, picked = 0, showReach = true;
  /* OPEN ON THE WHOLE COUNTRY. The overlapping reaches ARE the picture this prototype exists to
   * show; a view framed on one city hides every one of them and makes it look like the game it
   * is meant to be an alternative to. */
  function home() {
    /* FIT THE LAND, ON BOTH AXES, and centre on the LAND and not on a city — the overlapping
     * reaches are the picture this prototype exists to show, and a view framed on one city hides
     * every one of them. Both axes, because fitting the larger one leaves the other overflowing
     * and fitting the smaller leaves half the screen empty. */
    cam.x = WORLD.w / 2; cam.y = WORLD.h / 2;
    cam.z = Math.max(0.03, Math.min(innerWidth / WORLD.w, (innerHeight - 150) / WORLD.h) * 0.96);
  }
  const s2w = (sx, sy) => ({ x: cam.x + (sx - cv.width / 2 / DPR) / cam.z, y: cam.y + (sy - cv.height / 2 / DPR) / cam.z });
  const w2s = (x, y) => ({ x: (x - cam.x) * cam.z + cv.width / 2 / DPR, y: (y - cam.y) * cam.z + cv.height / 2 / DPR });

  const TERRA = { 1: '#16283c', 2: '#3a4438', 3: '#5d6642', 4: '#69713f', 5: '#33502f', 6: '#6d6247', 7: '#4a4553' };
  let bake = null;
  function bakeLand() {
    bake = document.createElement('canvas');
    bake.width = LW; bake.height = LH;
    const b = bake.getContext('2d'), im = b.createImageData(LW, LH);
    for (let i = 0; i < LW * LH; i++) {
      const col = TERRA[land.terra[i]] || '#000';
      im.data[i * 4] = parseInt(col.slice(1, 3), 16);
      im.data[i * 4 + 1] = parseInt(col.slice(3, 5), 16);
      im.data[i * 4 + 2] = parseInt(col.slice(5, 7), 16);
      im.data[i * 4 + 3] = 255;
    }
    b.putImageData(im, 0, 0);
  }

  let DPR = 1;
  function resize() {
    DPR = Math.min(2, window.devicePixelRatio || 1);
    cv.width = innerWidth * DPR; cv.height = innerHeight * DPR;
    g.setTransform(DPR, 0, 0, DPR, 0, 0);
  }
  function draw() {
    const w = cv.width / DPR, h = cv.height / DPR;
    g.setTransform(DPR, 0, 0, DPR, 0, 0);
    g.fillStyle = '#0d0b18'; g.fillRect(0, 0, w, h);
    const o = w2s(0, 0);
    g.imageSmoothingEnabled = false;
    g.drawImage(bake, o.x, o.y, LW * P.cell * cam.z, LH * P.cell * cam.z);

    /* THE REACHES, which are the whole point of the picture: yours filled, everyone else's
     * outlined, and the OVERLAPS are where two companies can both be ordered — which is where
     * every fight in this prototype happens, without anybody having designed a border. */
    if (showReach) for (const c of cities) {
      const p = w2s(c.x, c.y), r = c.reach * cam.z;
      const col = c.owner < 0 ? '#8a8a8a' : TINT[c.owner];
      g.beginPath(); g.arc(p.x, p.y, r, 0, 7);
      g.strokeStyle = col + (c.owner === 0 ? 'cc' : '66');
      g.lineWidth = c.owner === 0 ? 2 : 1; g.stroke();
      if (c.owner === 0) { g.fillStyle = col + '10'; g.fill(); }
    }
    /* the roads a company may actually take: city to city, only where a real path exists */
    g.lineWidth = 1;
    for (const c of cities) for (const id of c.nbrs) {
      if (id < c.id) continue;
      const a = w2s(c.x, c.y), b = w2s(cities[id].x, cities[id].y);
      g.strokeStyle = '#ffffff18';
      g.beginPath(); g.moveTo(a.x, a.y); g.lineTo(b.x, b.y); g.stroke();
    }
    for (const c of cities) {
      const p = w2s(c.x, c.y);
      const col = c.owner < 0 ? '#8a8a8a' : TINT[c.owner];
      g.beginPath(); g.arc(p.x, p.y, Math.max(6, P.court * cam.z), 0, 7);
      g.fillStyle = col + '22'; g.fill(); g.strokeStyle = col; g.lineWidth = 2; g.stroke();
      if (c.id === picked && c.owner === 0) {
        g.beginPath(); g.arc(p.x, p.y, Math.max(10, P.court * cam.z) + 5, 0, 7);
        g.strokeStyle = '#fff'; g.lineWidth = 1; g.stroke();
      }
      g.fillStyle = '#e8e2d4'; g.font = 'bold 11px system-ui'; g.textAlign = 'center';
      g.fillText(c.name, p.x, p.y - Math.max(8, P.court * cam.z) - 6);
      if (c.owner >= 0) {
        const bw = 34, hpf = Math.max(0, c.hp / c.maxHp);
        g.fillStyle = '#0009'; g.fillRect(p.x - bw / 2, p.y + Math.max(8, P.court * cam.z) + 3, bw, 3);
        g.fillStyle = col; g.fillRect(p.x - bw / 2, p.y + Math.max(8, P.court * cam.z) + 3, bw * hpf, 3);
      }
      if (c.hold) {
        g.fillStyle = TINT[c.hold.by]; g.font = '10px system-ui';
        g.fillText('taking ' + Math.ceil(P.take - (t - c.hold.since)) + 's', p.x, p.y + Math.max(8, P.court * cam.z) + 18);
      }
      if (c.order && c.owner >= 0) {
        const q = w2s(c.order.x, c.order.y);
        g.strokeStyle = col + '55'; g.setLineDash([3, 4]);
        g.beginPath(); g.moveTo(p.x, p.y); g.lineTo(q.x, q.y); g.stroke(); g.setLineDash([]);
        g.beginPath(); g.arc(q.x, q.y, 4, 0, 7); g.strokeStyle = col + '99'; g.stroke();
      }
    }
    for (const m of men) {
      const p = w2s(m.x, m.y);
      if (p.x < -10 || p.y < -10 || p.x > w + 10 || p.y > h + 10) continue;
      g.beginPath(); g.arc(p.x, p.y, 3, 0, 7);
      g.fillStyle = TINT[m.owner]; g.fill();
    }
    const mine = cities.filter((c) => c.owner === 0);
    $('tally').innerHTML = `<b>${mine.length}</b> of ${cities.length} cities &middot; ` +
      `<b>${men.filter((m) => m.owner === 0).length}</b> men &middot; ${Math.floor(t)}s` +
      `<br><span style="opacity:.7">zoom ${cam.z.toFixed(3)} &middot; land ${WORLD.w}&times;${WORLD.h} ` +
      `&middot; fields built ${builtFields}</span>`;
    $('legend').innerHTML = picked != null && cities[picked] && cities[picked].owner === 0
      ? `<b style="color:${TINT[0]}">${cities[picked].name}</b> — tap inside its ring to send its company`
      : 'you hold no city';
  }

  let sayT = 0;
  function say(m) { $('say').textContent = m; $('say').classList.add('on'); sayT = 2.6; }

  /* ---------------- input ---------------- */
  let drag = null, moved = 0;
  cv.addEventListener('pointerdown', (e) => { drag = { x: e.clientX, y: e.clientY }; moved = 0; });
  cv.addEventListener('pointermove', (e) => {
    if (!drag) return;
    const dx = e.clientX - drag.x, dy = e.clientY - drag.y;
    moved += Math.abs(dx) + Math.abs(dy);
    cam.x -= dx / cam.z; cam.y -= dy / cam.z;
    drag = { x: e.clientX, y: e.clientY };
  });
  cv.addEventListener('pointerup', (e) => {
    const wasDrag = moved > 8; drag = null;
    if (wasDrag) return;
    const p = s2w(e.clientX, e.clientY);
    const c = cities[picked];
    if (!c || c.owner !== 0) { say('you hold no city'); return; }
    /* THE RULE, AND THE ONLY REFUSAL IN THE PROTOTYPE. An order beyond the city's reach is not
     * a mistake to be corrected quietly — it is the thing being tested, so it says so. */
    if (!inReach(c, p.x, p.y)) { say('beyond ' + c.name + '’s reach — take a city nearer to it'); return; }
    if (!standable(p.x, p.y)) { say('the ground will not take them'); return; }
    if (!isFinite(at(fieldFor(c, p.x, p.y), c.x, c.y))) { say('no way there from ' + c.name); return; }
    c.order = { x: p.x, y: p.y };
  });
  cv.addEventListener('wheel', (e) => {
    e.preventDefault();
    cam.z = Math.max(0.08, Math.min(1.2, cam.z * (e.deltaY < 0 ? 1.12 : 0.89)));
  }, { passive: false });

  $('pick').addEventListener('click', () => {
    const mine = cities.filter((c) => c.owner === 0);
    if (!mine.length) { say('you hold no city'); return; }
    const i = mine.findIndex((c) => c.id === picked);
    picked = mine[(i + 1) % mine.length].id;
    const c = cities[picked];
    cam.x = c.x; cam.y = c.y;
    say(c.name + ' — ' + men.filter((m) => m.city === c.id).length + ' men');
  });
  $('reach').addEventListener('click', () => {
    showReach = !showReach; $('reach').classList.toggle('on', showReach);
  });
  $('again').addEventListener('click', () => { build((Math.random() * 0xffffffff) >>> 0); bakeLand(); });

  /* ---------------- the loop ---------------- */
  let last = 0, acc = 0;
  function frame(now) {
    const dt = Math.min(0.25, (now - last) / 1000 || 0); last = now;
    acc += dt;
    while (acc >= P.dt) { step(); acc -= P.dt; }
    if (sayT > 0) { sayT -= dt; if (sayT <= 0) $('say').classList.remove('on'); }
    draw();
    requestAnimationFrame(frame);
  }
  /* A PROTOTYPE THAT CANNOT BE MEASURED IS A PROTOTYPE THAT CANNOT BE BELIEVED. Everything is
   * in a closure, so one hook hands the numbers out — the same reason the renderer carries
   * `debugUnpatched` and nav carries `debugFields`. */
  window.__reach = () => ({ cam, WORLD, LW, LH, cell: P.cell, reach: cities[0] && cities[0].reach,
                            cities: cities.map((c) => ({ id: c.id, owner: c.owner, x: Math.round(c.x),
                                                         y: Math.round(c.y), hp: Math.round(c.hp),
                                                         nbrs: c.nbrs, men: men.filter((m) => m.city === c.id).length })),
                            men: men.length, fields: builtFields, t: Math.round(t) });
  addEventListener('resize', resize);
  resize();
  build(20261002);
  bakeLand();
  requestAnimationFrame(frame);
})();
